// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module decision_function (
        ap_clk,
        ap_rst,
        x_99_V_read,
        x_154_V_read,
        x_155_V_read,
        x_157_V_read,
        x_205_V_read,
        x_210_V_read,
        x_236_V_read,
        x_288_V_read,
        x_318_V_read,
        x_327_V_read,
        x_347_V_read,
        x_378_V_read,
        x_383_V_read,
        x_398_V_read,
        x_408_V_read,
        x_435_V_read,
        x_454_V_read,
        x_461_V_read,
        x_466_V_read,
        x_487_V_read,
        x_516_V_read,
        x_524_V_read,
        x_542_V_read,
        x_578_V_read,
        x_591_V_read,
        x_598_V_read,
        x_636_V_read,
        x_655_V_read,
        x_660_V_read,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [17:0] x_99_V_read;
input  [17:0] x_154_V_read;
input  [17:0] x_155_V_read;
input  [17:0] x_157_V_read;
input  [17:0] x_205_V_read;
input  [17:0] x_210_V_read;
input  [17:0] x_236_V_read;
input  [17:0] x_288_V_read;
input  [17:0] x_318_V_read;
input  [17:0] x_327_V_read;
input  [17:0] x_347_V_read;
input  [17:0] x_378_V_read;
input  [17:0] x_383_V_read;
input  [17:0] x_398_V_read;
input  [17:0] x_408_V_read;
input  [17:0] x_435_V_read;
input  [17:0] x_454_V_read;
input  [17:0] x_461_V_read;
input  [17:0] x_466_V_read;
input  [17:0] x_487_V_read;
input  [17:0] x_516_V_read;
input  [17:0] x_524_V_read;
input  [17:0] x_542_V_read;
input  [17:0] x_578_V_read;
input  [17:0] x_591_V_read;
input  [17:0] x_598_V_read;
input  [17:0] x_636_V_read;
input  [17:0] x_655_V_read;
input  [17:0] x_660_V_read;
output  [17:0] ap_return;
input   ap_ce;

reg[17:0] ap_return;

wire   [0:0] tmp_3_fu_380_p2;
reg   [0:0] tmp_3_reg_1320;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_3_reg_1320_pp0_iter1_reg;
reg   [0:0] tmp_3_reg_1320_pp0_iter2_reg;
wire   [0:0] tmp_3_1_fu_386_p2;
reg   [0:0] tmp_3_1_reg_1331;
wire   [0:0] tmp_3_2_fu_392_p2;
reg   [0:0] tmp_3_2_reg_1336;
wire   [0:0] tmp_3_3_fu_398_p2;
reg   [0:0] tmp_3_3_reg_1341;
wire   [0:0] tmp_3_4_fu_404_p2;
reg   [0:0] tmp_3_4_reg_1347;
wire   [0:0] tmp_3_7_fu_410_p2;
reg   [0:0] tmp_3_7_reg_1352;
wire   [0:0] tmp_3_s_fu_416_p2;
reg   [0:0] tmp_3_s_reg_1357;
wire   [0:0] tmp_3_5_fu_422_p2;
reg   [0:0] tmp_3_5_reg_1363;
wire   [0:0] tmp_3_6_fu_428_p2;
reg   [0:0] tmp_3_6_reg_1368;
wire   [0:0] tmp_3_8_fu_434_p2;
reg   [0:0] tmp_3_8_reg_1373;
wire   [0:0] tmp_3_9_fu_440_p2;
reg   [0:0] tmp_3_9_reg_1379;
reg   [0:0] tmp_3_9_reg_1379_pp0_iter1_reg;
wire   [0:0] tmp_3_10_fu_446_p2;
reg   [0:0] tmp_3_10_reg_1385;
reg   [0:0] tmp_3_10_reg_1385_pp0_iter1_reg;
wire   [0:0] tmp_3_11_fu_452_p2;
reg   [0:0] tmp_3_11_reg_1390;
reg   [0:0] tmp_3_11_reg_1390_pp0_iter1_reg;
wire   [0:0] tmp_3_12_fu_458_p2;
reg   [0:0] tmp_3_12_reg_1395;
reg   [0:0] tmp_3_12_reg_1395_pp0_iter1_reg;
wire   [0:0] tmp_3_13_fu_464_p2;
reg   [0:0] tmp_3_13_reg_1401;
reg   [0:0] tmp_3_13_reg_1401_pp0_iter1_reg;
wire   [0:0] tmp_3_14_fu_470_p2;
reg   [0:0] tmp_3_14_reg_1406;
reg   [0:0] tmp_3_14_reg_1406_pp0_iter1_reg;
wire   [0:0] tmp_3_15_fu_476_p2;
reg   [0:0] tmp_3_15_reg_1411;
reg   [0:0] tmp_3_15_reg_1411_pp0_iter1_reg;
wire   [0:0] tmp_3_16_fu_482_p2;
reg   [0:0] tmp_3_16_reg_1417;
reg   [0:0] tmp_3_16_reg_1417_pp0_iter1_reg;
reg   [0:0] tmp_3_16_reg_1417_pp0_iter2_reg;
wire   [0:0] tmp_3_17_fu_488_p2;
reg   [0:0] tmp_3_17_reg_1423;
reg   [0:0] tmp_3_17_reg_1423_pp0_iter1_reg;
reg   [0:0] tmp_3_17_reg_1423_pp0_iter2_reg;
wire   [0:0] tmp_3_18_fu_494_p2;
reg   [0:0] tmp_3_18_reg_1429;
reg   [0:0] tmp_3_18_reg_1429_pp0_iter1_reg;
reg   [0:0] tmp_3_18_reg_1429_pp0_iter2_reg;
wire   [0:0] tmp_3_19_fu_500_p2;
reg   [0:0] tmp_3_19_reg_1434;
reg   [0:0] tmp_3_19_reg_1434_pp0_iter1_reg;
reg   [0:0] tmp_3_19_reg_1434_pp0_iter2_reg;
wire   [0:0] tmp_3_20_fu_506_p2;
reg   [0:0] tmp_3_20_reg_1439;
reg   [0:0] tmp_3_20_reg_1439_pp0_iter1_reg;
reg   [0:0] tmp_3_20_reg_1439_pp0_iter2_reg;
wire   [0:0] tmp_3_21_fu_512_p2;
reg   [0:0] tmp_3_21_reg_1445;
reg   [0:0] tmp_3_21_reg_1445_pp0_iter1_reg;
reg   [0:0] tmp_3_21_reg_1445_pp0_iter2_reg;
wire   [0:0] tmp_3_22_fu_518_p2;
reg   [0:0] tmp_3_22_reg_1450;
reg   [0:0] tmp_3_22_reg_1450_pp0_iter1_reg;
reg   [0:0] tmp_3_22_reg_1450_pp0_iter2_reg;
wire   [0:0] tmp_3_23_fu_524_p2;
reg   [0:0] tmp_3_23_reg_1455;
reg   [0:0] tmp_3_23_reg_1455_pp0_iter1_reg;
reg   [0:0] tmp_3_23_reg_1455_pp0_iter2_reg;
wire   [0:0] tmp_3_24_fu_530_p2;
reg   [0:0] tmp_3_24_reg_1461;
reg   [0:0] tmp_3_24_reg_1461_pp0_iter1_reg;
reg   [0:0] tmp_3_24_reg_1461_pp0_iter2_reg;
reg   [0:0] tmp_3_24_reg_1461_pp0_iter3_reg;
wire   [0:0] tmp_3_25_fu_536_p2;
reg   [0:0] tmp_3_25_reg_1467;
reg   [0:0] tmp_3_25_reg_1467_pp0_iter1_reg;
reg   [0:0] tmp_3_25_reg_1467_pp0_iter2_reg;
reg   [0:0] tmp_3_25_reg_1467_pp0_iter3_reg;
wire   [0:0] tmp_3_26_fu_542_p2;
reg   [0:0] tmp_3_26_reg_1472;
reg   [0:0] tmp_3_26_reg_1472_pp0_iter1_reg;
reg   [0:0] tmp_3_26_reg_1472_pp0_iter2_reg;
reg   [0:0] tmp_3_26_reg_1472_pp0_iter3_reg;
wire   [0:0] tmp_3_27_fu_548_p2;
reg   [0:0] tmp_3_27_reg_1477;
reg   [0:0] tmp_3_27_reg_1477_pp0_iter1_reg;
reg   [0:0] tmp_3_27_reg_1477_pp0_iter2_reg;
reg   [0:0] tmp_3_27_reg_1477_pp0_iter3_reg;
reg   [0:0] tmp_3_27_reg_1477_pp0_iter4_reg;
wire   [0:0] tmp_3_28_fu_554_p2;
reg   [0:0] tmp_3_28_reg_1483;
reg   [0:0] tmp_3_28_reg_1483_pp0_iter1_reg;
reg   [0:0] tmp_3_28_reg_1483_pp0_iter2_reg;
reg   [0:0] tmp_3_28_reg_1483_pp0_iter3_reg;
wire   [0:0] tmp_3_29_fu_560_p2;
reg   [0:0] tmp_3_29_reg_1488;
reg   [0:0] tmp_3_29_reg_1488_pp0_iter1_reg;
reg   [0:0] tmp_3_29_reg_1488_pp0_iter2_reg;
reg   [0:0] tmp_3_29_reg_1488_pp0_iter3_reg;
reg   [0:0] tmp_3_29_reg_1488_pp0_iter4_reg;
wire   [0:0] p_s_fu_566_p2;
reg   [0:0] p_s_reg_1493;
reg   [0:0] p_s_reg_1493_pp0_iter1_reg;
wire   [0:0] p_s_41_fu_572_p2;
reg   [0:0] p_s_41_reg_1502;
wire   [0:0] p_36_s_fu_648_p2;
reg   [0:0] p_36_s_reg_1511;
wire   [0:0] p_36_s_47_fu_653_p2;
reg   [0:0] p_36_s_47_reg_1517;
wire   [0:0] p_2_fu_663_p2;
reg   [0:0] p_2_reg_1523;
wire   [3:0] tmp_8_fu_756_p3;
reg   [3:0] tmp_8_reg_1529;
wire   [0:0] p_40_s_fu_811_p2;
reg   [0:0] p_40_s_reg_1534;
wire   [0:0] p_40_s_51_fu_816_p2;
reg   [0:0] p_40_s_51_reg_1540;
wire   [0:0] p_40_s_52_fu_821_p2;
reg   [0:0] p_40_s_52_reg_1546;
wire   [0:0] p_2_57_fu_831_p2;
reg   [0:0] p_2_57_reg_1551;
wire   [0:0] brmerge12_fu_874_p2;
reg   [0:0] brmerge12_reg_1557;
wire   [4:0] tmp_15_fu_938_p3;
reg   [4:0] tmp_15_reg_1563;
wire   [0:0] p_40_1_58_fu_1000_p2;
reg   [0:0] p_40_1_58_reg_1568;
wire   [0:0] p_40_44_s_fu_1004_p2;
reg   [0:0] p_40_44_s_reg_1574;
wire   [0:0] p_3_fu_1014_p2;
reg   [0:0] p_3_reg_1580;
reg   [0:0] p_3_reg_1580_pp0_iter4_reg;
wire   [0:0] brmerge18_fu_1051_p2;
reg   [0:0] brmerge18_reg_1586;
wire   [4:0] tmp_23_fu_1109_p3;
reg   [4:0] tmp_23_reg_1593;
wire   [0:0] brmerge24_fu_1170_p2;
reg   [0:0] brmerge24_reg_1598;
wire   [4:0] tmp_29_fu_1215_p3;
reg   [4:0] tmp_29_reg_1603;
wire    ap_block_pp0_stage0;
wire   [0:0] p_s_42_fu_578_p2;
wire   [0:0] not_tmp_3_3_fu_587_p2;
wire   [0:0] tmp1_fu_592_p2;
wire   [0:0] not_tmp_3_2_fu_602_p2;
wire   [0:0] p_1_fu_607_p2;
wire   [0:0] p_34_s_fu_612_p2;
wire   [0:0] not_tmp_3_s_fu_622_p2;
wire   [0:0] tmp2_fu_627_p2;
wire   [0:0] not_tmp_3_1_fu_638_p2;
wire   [0:0] p_1_46_fu_643_p2;
wire   [0:0] not_tmp_3_5_fu_658_p2;
wire   [0:0] p_33_s_fu_597_p2;
wire   [0:0] p_34_s_44_fu_617_p2;
wire   [0:0] brmerge2_fu_680_p2;
wire   [0:0] p_34_s_45_fu_632_p2;
wire   [0:0] p_s_43_fu_582_p2;
wire   [0:0] not_s_fu_691_p2;
wire   [1:0] tmp_cast_fu_697_p1;
wire   [0:0] brmerge_fu_669_p2;
wire   [1:0] tmp_1_fu_701_p3;
wire   [1:0] tmp_2_fu_709_p3;
wire   [2:0] tmp_2_cast_fu_717_p1;
wire   [0:0] brmerge1_fu_675_p2;
wire   [2:0] tmp_4_fu_721_p3;
wire   [2:0] tmp_5_fu_728_p3;
wire   [0:0] brmerge3_fu_685_p2;
wire   [2:0] tmp_6_fu_736_p3;
wire   [2:0] tmp_7_fu_744_p3;
wire   [3:0] tmp_7_cast_fu_752_p1;
wire   [0:0] not_tmp_3_4_fu_767_p2;
wire   [0:0] tmp3_fu_772_p2;
wire   [0:0] p_36_1_fu_782_p2;
wire   [0:0] not_tmp_3_6_fu_791_p2;
wire   [0:0] tmp4_fu_796_p2;
wire   [0:0] not_tmp_3_fu_806_p2;
wire   [0:0] not_tmp_3_10_fu_826_p2;
wire   [0:0] p_36_s_48_fu_763_p2;
wire   [0:0] brmerge5_fu_842_p2;
wire   [0:0] p_36_s_49_fu_777_p2;
wire   [0:0] brmerge7_fu_852_p2;
wire   [0:0] p_36_38_s_fu_786_p2;
wire   [0:0] brmerge9_fu_862_p2;
wire   [0:0] p_36_s_50_fu_801_p2;
wire   [0:0] brmerge4_fu_837_p2;
wire   [3:0] tmp_9_fu_879_p3;
wire   [0:0] brmerge6_fu_846_p2;
wire   [3:0] tmp_s_fu_886_p3;
wire   [3:0] tmp_10_fu_894_p3;
wire   [0:0] brmerge8_fu_856_p2;
wire   [3:0] tmp_11_fu_902_p3;
wire   [3:0] tmp_12_fu_910_p3;
wire   [0:0] brmerge10_fu_868_p2;
wire   [3:0] tmp_13_fu_918_p3;
wire   [3:0] tmp_14_fu_926_p3;
wire   [4:0] tmp_14_cast_fu_934_p1;
wire   [0:0] not_tmp_3_7_fu_949_p2;
wire   [0:0] tmp5_fu_954_p2;
wire   [0:0] not_tmp_3_8_fu_964_p2;
wire   [0:0] p_40_s_55_fu_969_p2;
wire   [0:0] p_40_1_fu_974_p2;
wire   [0:0] not_tmp_3_9_fu_984_p2;
wire   [0:0] tmp6_fu_989_p2;
wire   [0:0] not_tmp_3_12_fu_1009_p2;
wire   [0:0] p_40_s_53_fu_945_p2;
wire   [0:0] p_40_s_54_fu_959_p2;
wire   [0:0] brmerge14_fu_1029_p2;
wire   [0:0] p_40_42_s_fu_979_p2;
wire   [0:0] brmerge16_fu_1039_p2;
wire   [0:0] p_40_s_56_fu_994_p2;
wire   [0:0] brmerge11_fu_1019_p2;
wire   [4:0] tmp_16_fu_1055_p3;
wire   [0:0] brmerge13_fu_1024_p2;
wire   [4:0] tmp_17_fu_1062_p3;
wire   [4:0] tmp_18_fu_1069_p3;
wire   [0:0] brmerge15_fu_1033_p2;
wire   [4:0] tmp_19_fu_1077_p3;
wire   [4:0] tmp_20_fu_1085_p3;
wire   [0:0] brmerge17_fu_1045_p2;
wire   [4:0] tmp_21_fu_1093_p3;
wire   [4:0] tmp_22_fu_1101_p3;
wire   [0:0] not_tmp_3_11_fu_1121_p2;
wire   [0:0] tmp7_fu_1126_p2;
wire   [0:0] p_40_2_fu_1136_p2;
wire   [0:0] p_40_44_s_59_fu_1117_p2;
wire   [0:0] brmerge20_fu_1150_p2;
wire   [0:0] p_40_44_s_60_fu_1131_p2;
wire   [0:0] brmerge22_fu_1160_p2;
wire   [0:0] p_40_46_s_fu_1140_p2;
wire   [0:0] brmerge19_fu_1145_p2;
wire   [4:0] tmp_24_fu_1176_p3;
wire   [0:0] brmerge21_fu_1154_p2;
wire   [4:0] tmp_25_fu_1183_p3;
wire   [4:0] tmp_26_fu_1191_p3;
wire   [0:0] brmerge23_fu_1164_p2;
wire   [4:0] tmp_27_fu_1199_p3;
wire   [4:0] tmp_28_fu_1207_p3;
wire   [0:0] not_tmp_3_13_fu_1223_p2;
wire   [0:0] tmp8_fu_1228_p2;
wire   [0:0] p_40_s_61_fu_1233_p2;
wire   [0:0] brmerge25_fu_1238_p2;
wire   [4:0] tmp_fu_1250_p33;
wire   [17:0] tmp_fu_1250_p34;
reg    ap_ce_reg;
reg   [17:0] x_99_V_read_int_reg;
reg   [17:0] x_154_V_read_int_reg;
reg   [17:0] x_155_V_read_int_reg;
reg   [17:0] x_157_V_read_int_reg;
reg   [17:0] x_205_V_read_int_reg;
reg   [17:0] x_210_V_read_int_reg;
reg   [17:0] x_236_V_read_int_reg;
reg   [17:0] x_288_V_read_int_reg;
reg   [17:0] x_318_V_read_int_reg;
reg   [17:0] x_327_V_read_int_reg;
reg   [17:0] x_347_V_read_int_reg;
reg   [17:0] x_378_V_read_int_reg;
reg   [17:0] x_383_V_read_int_reg;
reg   [17:0] x_398_V_read_int_reg;
reg   [17:0] x_408_V_read_int_reg;
reg   [17:0] x_435_V_read_int_reg;
reg   [17:0] x_454_V_read_int_reg;
reg   [17:0] x_461_V_read_int_reg;
reg   [17:0] x_466_V_read_int_reg;
reg   [17:0] x_487_V_read_int_reg;
reg   [17:0] x_516_V_read_int_reg;
reg   [17:0] x_524_V_read_int_reg;
reg   [17:0] x_542_V_read_int_reg;
reg   [17:0] x_578_V_read_int_reg;
reg   [17:0] x_591_V_read_int_reg;
reg   [17:0] x_598_V_read_int_reg;
reg   [17:0] x_636_V_read_int_reg;
reg   [17:0] x_655_V_read_int_reg;
reg   [17:0] x_660_V_read_int_reg;
reg   [17:0] ap_return_int_reg;

my_prj_mux_325_18_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 18 ),
    .din3_WIDTH( 18 ),
    .din4_WIDTH( 18 ),
    .din5_WIDTH( 18 ),
    .din6_WIDTH( 18 ),
    .din7_WIDTH( 18 ),
    .din8_WIDTH( 18 ),
    .din9_WIDTH( 18 ),
    .din10_WIDTH( 18 ),
    .din11_WIDTH( 18 ),
    .din12_WIDTH( 18 ),
    .din13_WIDTH( 18 ),
    .din14_WIDTH( 18 ),
    .din15_WIDTH( 18 ),
    .din16_WIDTH( 18 ),
    .din17_WIDTH( 18 ),
    .din18_WIDTH( 18 ),
    .din19_WIDTH( 18 ),
    .din20_WIDTH( 18 ),
    .din21_WIDTH( 18 ),
    .din22_WIDTH( 18 ),
    .din23_WIDTH( 18 ),
    .din24_WIDTH( 18 ),
    .din25_WIDTH( 18 ),
    .din26_WIDTH( 18 ),
    .din27_WIDTH( 18 ),
    .din28_WIDTH( 18 ),
    .din29_WIDTH( 18 ),
    .din30_WIDTH( 18 ),
    .din31_WIDTH( 18 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 18 ))
my_prj_mux_325_18_1_0_U64(
    .din0(18'd2),
    .din1(18'd77),
    .din2(18'd0),
    .din3(18'd0),
    .din4(18'd4),
    .din5(18'd44),
    .din6(18'd269),
    .din7(18'd56),
    .din8(18'd14),
    .din9(18'd19),
    .din10(18'd4),
    .din11(18'd0),
    .din12(18'd6),
    .din13(18'd10),
    .din14(18'd0),
    .din15(18'd17),
    .din16(18'd177),
    .din17(18'd49),
    .din18(18'd0),
    .din19(18'd13),
    .din20(18'd144),
    .din21(18'd315),
    .din22(18'd23),
    .din23(18'd49),
    .din24(18'd1),
    .din25(18'd1),
    .din26(18'd0),
    .din27(18'd0),
    .din28(18'd0),
    .din29(18'd9),
    .din30(18'd0),
    .din31(18'd4),
    .din32(tmp_fu_1250_p33),
    .dout(tmp_fu_1250_p34)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= tmp_fu_1250_p34;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge12_reg_1557 <= brmerge12_fu_874_p2;
        brmerge18_reg_1586 <= brmerge18_fu_1051_p2;
        brmerge24_reg_1598 <= brmerge24_fu_1170_p2;
        p_2_57_reg_1551 <= p_2_57_fu_831_p2;
        p_3_reg_1580 <= p_3_fu_1014_p2;
        p_3_reg_1580_pp0_iter4_reg <= p_3_reg_1580;
        p_40_1_58_reg_1568 <= p_40_1_58_fu_1000_p2;
        p_40_44_s_reg_1574 <= p_40_44_s_fu_1004_p2;
        p_40_s_51_reg_1540 <= p_40_s_51_fu_816_p2;
        p_40_s_52_reg_1546 <= p_40_s_52_fu_821_p2;
        p_40_s_reg_1534 <= p_40_s_fu_811_p2;
        p_s_41_reg_1502 <= p_s_41_fu_572_p2;
        p_s_reg_1493 <= p_s_fu_566_p2;
        p_s_reg_1493_pp0_iter1_reg <= p_s_reg_1493;
        tmp_15_reg_1563 <= tmp_15_fu_938_p3;
        tmp_23_reg_1593 <= tmp_23_fu_1109_p3;
        tmp_29_reg_1603 <= tmp_29_fu_1215_p3;
        tmp_3_10_reg_1385 <= tmp_3_10_fu_446_p2;
        tmp_3_10_reg_1385_pp0_iter1_reg <= tmp_3_10_reg_1385;
        tmp_3_11_reg_1390 <= tmp_3_11_fu_452_p2;
        tmp_3_11_reg_1390_pp0_iter1_reg <= tmp_3_11_reg_1390;
        tmp_3_12_reg_1395 <= tmp_3_12_fu_458_p2;
        tmp_3_12_reg_1395_pp0_iter1_reg <= tmp_3_12_reg_1395;
        tmp_3_13_reg_1401 <= tmp_3_13_fu_464_p2;
        tmp_3_13_reg_1401_pp0_iter1_reg <= tmp_3_13_reg_1401;
        tmp_3_14_reg_1406 <= tmp_3_14_fu_470_p2;
        tmp_3_14_reg_1406_pp0_iter1_reg <= tmp_3_14_reg_1406;
        tmp_3_15_reg_1411 <= tmp_3_15_fu_476_p2;
        tmp_3_15_reg_1411_pp0_iter1_reg <= tmp_3_15_reg_1411;
        tmp_3_16_reg_1417 <= tmp_3_16_fu_482_p2;
        tmp_3_16_reg_1417_pp0_iter1_reg <= tmp_3_16_reg_1417;
        tmp_3_16_reg_1417_pp0_iter2_reg <= tmp_3_16_reg_1417_pp0_iter1_reg;
        tmp_3_17_reg_1423 <= tmp_3_17_fu_488_p2;
        tmp_3_17_reg_1423_pp0_iter1_reg <= tmp_3_17_reg_1423;
        tmp_3_17_reg_1423_pp0_iter2_reg <= tmp_3_17_reg_1423_pp0_iter1_reg;
        tmp_3_18_reg_1429 <= tmp_3_18_fu_494_p2;
        tmp_3_18_reg_1429_pp0_iter1_reg <= tmp_3_18_reg_1429;
        tmp_3_18_reg_1429_pp0_iter2_reg <= tmp_3_18_reg_1429_pp0_iter1_reg;
        tmp_3_19_reg_1434 <= tmp_3_19_fu_500_p2;
        tmp_3_19_reg_1434_pp0_iter1_reg <= tmp_3_19_reg_1434;
        tmp_3_19_reg_1434_pp0_iter2_reg <= tmp_3_19_reg_1434_pp0_iter1_reg;
        tmp_3_1_reg_1331 <= tmp_3_1_fu_386_p2;
        tmp_3_20_reg_1439 <= tmp_3_20_fu_506_p2;
        tmp_3_20_reg_1439_pp0_iter1_reg <= tmp_3_20_reg_1439;
        tmp_3_20_reg_1439_pp0_iter2_reg <= tmp_3_20_reg_1439_pp0_iter1_reg;
        tmp_3_21_reg_1445 <= tmp_3_21_fu_512_p2;
        tmp_3_21_reg_1445_pp0_iter1_reg <= tmp_3_21_reg_1445;
        tmp_3_21_reg_1445_pp0_iter2_reg <= tmp_3_21_reg_1445_pp0_iter1_reg;
        tmp_3_22_reg_1450 <= tmp_3_22_fu_518_p2;
        tmp_3_22_reg_1450_pp0_iter1_reg <= tmp_3_22_reg_1450;
        tmp_3_22_reg_1450_pp0_iter2_reg <= tmp_3_22_reg_1450_pp0_iter1_reg;
        tmp_3_23_reg_1455 <= tmp_3_23_fu_524_p2;
        tmp_3_23_reg_1455_pp0_iter1_reg <= tmp_3_23_reg_1455;
        tmp_3_23_reg_1455_pp0_iter2_reg <= tmp_3_23_reg_1455_pp0_iter1_reg;
        tmp_3_24_reg_1461 <= tmp_3_24_fu_530_p2;
        tmp_3_24_reg_1461_pp0_iter1_reg <= tmp_3_24_reg_1461;
        tmp_3_24_reg_1461_pp0_iter2_reg <= tmp_3_24_reg_1461_pp0_iter1_reg;
        tmp_3_24_reg_1461_pp0_iter3_reg <= tmp_3_24_reg_1461_pp0_iter2_reg;
        tmp_3_25_reg_1467 <= tmp_3_25_fu_536_p2;
        tmp_3_25_reg_1467_pp0_iter1_reg <= tmp_3_25_reg_1467;
        tmp_3_25_reg_1467_pp0_iter2_reg <= tmp_3_25_reg_1467_pp0_iter1_reg;
        tmp_3_25_reg_1467_pp0_iter3_reg <= tmp_3_25_reg_1467_pp0_iter2_reg;
        tmp_3_26_reg_1472 <= tmp_3_26_fu_542_p2;
        tmp_3_26_reg_1472_pp0_iter1_reg <= tmp_3_26_reg_1472;
        tmp_3_26_reg_1472_pp0_iter2_reg <= tmp_3_26_reg_1472_pp0_iter1_reg;
        tmp_3_26_reg_1472_pp0_iter3_reg <= tmp_3_26_reg_1472_pp0_iter2_reg;
        tmp_3_27_reg_1477 <= tmp_3_27_fu_548_p2;
        tmp_3_27_reg_1477_pp0_iter1_reg <= tmp_3_27_reg_1477;
        tmp_3_27_reg_1477_pp0_iter2_reg <= tmp_3_27_reg_1477_pp0_iter1_reg;
        tmp_3_27_reg_1477_pp0_iter3_reg <= tmp_3_27_reg_1477_pp0_iter2_reg;
        tmp_3_27_reg_1477_pp0_iter4_reg <= tmp_3_27_reg_1477_pp0_iter3_reg;
        tmp_3_28_reg_1483 <= tmp_3_28_fu_554_p2;
        tmp_3_28_reg_1483_pp0_iter1_reg <= tmp_3_28_reg_1483;
        tmp_3_28_reg_1483_pp0_iter2_reg <= tmp_3_28_reg_1483_pp0_iter1_reg;
        tmp_3_28_reg_1483_pp0_iter3_reg <= tmp_3_28_reg_1483_pp0_iter2_reg;
        tmp_3_29_reg_1488 <= tmp_3_29_fu_560_p2;
        tmp_3_29_reg_1488_pp0_iter1_reg <= tmp_3_29_reg_1488;
        tmp_3_29_reg_1488_pp0_iter2_reg <= tmp_3_29_reg_1488_pp0_iter1_reg;
        tmp_3_29_reg_1488_pp0_iter3_reg <= tmp_3_29_reg_1488_pp0_iter2_reg;
        tmp_3_29_reg_1488_pp0_iter4_reg <= tmp_3_29_reg_1488_pp0_iter3_reg;
        tmp_3_2_reg_1336 <= tmp_3_2_fu_392_p2;
        tmp_3_3_reg_1341 <= tmp_3_3_fu_398_p2;
        tmp_3_4_reg_1347 <= tmp_3_4_fu_404_p2;
        tmp_3_5_reg_1363 <= tmp_3_5_fu_422_p2;
        tmp_3_6_reg_1368 <= tmp_3_6_fu_428_p2;
        tmp_3_7_reg_1352 <= tmp_3_7_fu_410_p2;
        tmp_3_8_reg_1373 <= tmp_3_8_fu_434_p2;
        tmp_3_9_reg_1379 <= tmp_3_9_fu_440_p2;
        tmp_3_9_reg_1379_pp0_iter1_reg <= tmp_3_9_reg_1379;
        tmp_3_reg_1320 <= tmp_3_fu_380_p2;
        tmp_3_reg_1320_pp0_iter1_reg <= tmp_3_reg_1320;
        tmp_3_reg_1320_pp0_iter2_reg <= tmp_3_reg_1320_pp0_iter1_reg;
        tmp_3_s_reg_1357 <= tmp_3_s_fu_416_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_3_reg_1320 == 1'd1))) begin
        p_2_reg_1523 <= p_2_fu_663_p2;
        p_36_s_47_reg_1517 <= p_36_s_47_fu_653_p2;
        p_36_s_reg_1511 <= p_36_s_fu_648_p2;
        tmp_8_reg_1529 <= tmp_8_fu_756_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_154_V_read_int_reg <= x_154_V_read;
        x_155_V_read_int_reg <= x_155_V_read;
        x_157_V_read_int_reg <= x_157_V_read;
        x_205_V_read_int_reg <= x_205_V_read;
        x_210_V_read_int_reg <= x_210_V_read;
        x_236_V_read_int_reg <= x_236_V_read;
        x_288_V_read_int_reg <= x_288_V_read;
        x_318_V_read_int_reg <= x_318_V_read;
        x_327_V_read_int_reg <= x_327_V_read;
        x_347_V_read_int_reg <= x_347_V_read;
        x_378_V_read_int_reg <= x_378_V_read;
        x_383_V_read_int_reg <= x_383_V_read;
        x_398_V_read_int_reg <= x_398_V_read;
        x_408_V_read_int_reg <= x_408_V_read;
        x_435_V_read_int_reg <= x_435_V_read;
        x_454_V_read_int_reg <= x_454_V_read;
        x_461_V_read_int_reg <= x_461_V_read;
        x_466_V_read_int_reg <= x_466_V_read;
        x_487_V_read_int_reg <= x_487_V_read;
        x_516_V_read_int_reg <= x_516_V_read;
        x_524_V_read_int_reg <= x_524_V_read;
        x_542_V_read_int_reg <= x_542_V_read;
        x_578_V_read_int_reg <= x_578_V_read;
        x_591_V_read_int_reg <= x_591_V_read;
        x_598_V_read_int_reg <= x_598_V_read;
        x_636_V_read_int_reg <= x_636_V_read;
        x_655_V_read_int_reg <= x_655_V_read;
        x_660_V_read_int_reg <= x_660_V_read;
        x_99_V_read_int_reg <= x_99_V_read;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = tmp_fu_1250_p34;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign brmerge10_fu_868_p2 = (p_36_s_50_fu_801_p2 | brmerge9_fu_862_p2);

assign brmerge11_fu_1019_p2 = (tmp_3_reg_1320_pp0_iter2_reg | p_40_s_53_fu_945_p2);

assign brmerge12_fu_874_p2 = (tmp_3_reg_1320_pp0_iter1_reg | p_40_s_52_fu_821_p2);

assign brmerge13_fu_1024_p2 = (p_40_s_54_fu_959_p2 | brmerge12_reg_1557);

assign brmerge14_fu_1029_p2 = (tmp_3_reg_1320_pp0_iter2_reg | p_40_s_51_reg_1540);

assign brmerge15_fu_1033_p2 = (p_40_42_s_fu_979_p2 | brmerge14_fu_1029_p2);

assign brmerge16_fu_1039_p2 = (p_40_1_fu_974_p2 | brmerge14_fu_1029_p2);

assign brmerge17_fu_1045_p2 = (p_40_s_56_fu_994_p2 | brmerge16_fu_1039_p2);

assign brmerge18_fu_1051_p2 = (tmp_3_reg_1320_pp0_iter2_reg | p_40_s_reg_1534);

assign brmerge19_fu_1145_p2 = (p_40_44_s_59_fu_1117_p2 | brmerge18_reg_1586);

assign brmerge1_fu_675_p2 = (p_s_41_reg_1502 | p_34_s_44_fu_617_p2);

assign brmerge20_fu_1150_p2 = (p_40_44_s_reg_1574 | brmerge18_reg_1586);

assign brmerge21_fu_1154_p2 = (p_40_44_s_60_fu_1131_p2 | brmerge20_fu_1150_p2);

assign brmerge22_fu_1160_p2 = (p_40_1_58_reg_1568 | brmerge18_reg_1586);

assign brmerge23_fu_1164_p2 = (p_40_46_s_fu_1140_p2 | brmerge22_fu_1160_p2);

assign brmerge24_fu_1170_p2 = (p_40_2_fu_1136_p2 | brmerge22_fu_1160_p2);

assign brmerge25_fu_1238_p2 = (p_40_s_61_fu_1233_p2 | brmerge24_reg_1598);

assign brmerge2_fu_680_p2 = (p_s_41_reg_1502 | p_34_s_fu_612_p2);

assign brmerge3_fu_685_p2 = (p_34_s_45_fu_632_p2 | brmerge2_fu_680_p2);

assign brmerge4_fu_837_p2 = (p_s_reg_1493_pp0_iter1_reg | p_36_s_48_fu_763_p2);

assign brmerge5_fu_842_p2 = (p_s_reg_1493_pp0_iter1_reg | p_36_s_47_reg_1517);

assign brmerge6_fu_846_p2 = (p_36_s_49_fu_777_p2 | brmerge5_fu_842_p2);

assign brmerge7_fu_852_p2 = (p_s_reg_1493_pp0_iter1_reg | p_36_s_reg_1511);

assign brmerge8_fu_856_p2 = (p_36_38_s_fu_786_p2 | brmerge7_fu_852_p2);

assign brmerge9_fu_862_p2 = (p_36_1_fu_782_p2 | brmerge7_fu_852_p2);

assign brmerge_fu_669_p2 = (p_s_42_fu_578_p2 | p_33_s_fu_597_p2);

assign not_s_fu_691_p2 = (p_s_43_fu_582_p2 ^ 1'd1);

assign not_tmp_3_10_fu_826_p2 = (tmp_3_15_reg_1411_pp0_iter1_reg ^ 1'd1);

assign not_tmp_3_11_fu_1121_p2 = (tmp_3_24_reg_1461_pp0_iter3_reg ^ 1'd1);

assign not_tmp_3_12_fu_1009_p2 = (tmp_3_23_reg_1455_pp0_iter2_reg ^ 1'd1);

assign not_tmp_3_13_fu_1223_p2 = (tmp_3_27_reg_1477_pp0_iter4_reg ^ 1'd1);

assign not_tmp_3_1_fu_638_p2 = (tmp_3_1_reg_1331 ^ 1'd1);

assign not_tmp_3_2_fu_602_p2 = (tmp_3_2_reg_1336 ^ 1'd1);

assign not_tmp_3_3_fu_587_p2 = (tmp_3_3_reg_1341 ^ 1'd1);

assign not_tmp_3_4_fu_767_p2 = (tmp_3_9_reg_1379_pp0_iter1_reg ^ 1'd1);

assign not_tmp_3_5_fu_658_p2 = (tmp_3_8_reg_1373 ^ 1'd1);

assign not_tmp_3_6_fu_791_p2 = (tmp_3_12_reg_1395_pp0_iter1_reg ^ 1'd1);

assign not_tmp_3_7_fu_949_p2 = (tmp_3_17_reg_1423_pp0_iter2_reg ^ 1'd1);

assign not_tmp_3_8_fu_964_p2 = (tmp_3_16_reg_1417_pp0_iter2_reg ^ 1'd1);

assign not_tmp_3_9_fu_984_p2 = (tmp_3_20_reg_1439_pp0_iter2_reg ^ 1'd1);

assign not_tmp_3_fu_806_p2 = (tmp_3_reg_1320_pp0_iter1_reg ^ 1'd1);

assign not_tmp_3_s_fu_622_p2 = (tmp_3_s_reg_1357 ^ 1'd1);

assign p_1_46_fu_643_p2 = (tmp_3_reg_1320 & not_tmp_3_1_fu_638_p2);

assign p_1_fu_607_p2 = (p_s_reg_1493 & not_tmp_3_2_fu_602_p2);

assign p_2_57_fu_831_p2 = (not_tmp_3_fu_806_p2 & not_tmp_3_10_fu_826_p2);

assign p_2_fu_663_p2 = (p_1_46_fu_643_p2 & not_tmp_3_5_fu_658_p2);

assign p_33_s_fu_597_p2 = (tmp1_fu_592_p2 & p_s_41_reg_1502);

assign p_34_s_44_fu_617_p2 = (tmp_3_5_reg_1363 & p_34_s_fu_612_p2);

assign p_34_s_45_fu_632_p2 = (tmp2_fu_627_p2 & p_1_fu_607_p2);

assign p_34_s_fu_612_p2 = (tmp_3_s_reg_1357 & p_1_fu_607_p2);

assign p_36_1_fu_782_p2 = (tmp_3_12_reg_1395_pp0_iter1_reg & p_2_reg_1523);

assign p_36_38_s_fu_786_p2 = (tmp_3_13_reg_1401_pp0_iter1_reg & p_36_1_fu_782_p2);

assign p_36_s_47_fu_653_p2 = (tmp_3_9_reg_1379 & p_36_s_fu_648_p2);

assign p_36_s_48_fu_763_p2 = (tmp_3_10_reg_1385_pp0_iter1_reg & p_36_s_47_reg_1517);

assign p_36_s_49_fu_777_p2 = (tmp3_fu_772_p2 & p_36_s_reg_1511);

assign p_36_s_50_fu_801_p2 = (tmp4_fu_796_p2 & p_2_reg_1523);

assign p_36_s_fu_648_p2 = (tmp_3_8_reg_1373 & p_1_46_fu_643_p2);

assign p_3_fu_1014_p2 = (p_2_57_reg_1551 & not_tmp_3_12_fu_1009_p2);

assign p_40_1_58_fu_1000_p2 = (tmp_3_23_reg_1455_pp0_iter2_reg & p_2_57_reg_1551);

assign p_40_1_fu_974_p2 = (tmp_3_20_reg_1439_pp0_iter2_reg & p_40_s_55_fu_969_p2);

assign p_40_2_fu_1136_p2 = (tmp_3_27_reg_1477_pp0_iter3_reg & p_3_reg_1580);

assign p_40_42_s_fu_979_p2 = (tmp_3_21_reg_1445_pp0_iter2_reg & p_40_1_fu_974_p2);

assign p_40_44_s_59_fu_1117_p2 = (tmp_3_25_reg_1467_pp0_iter3_reg & p_40_44_s_reg_1574);

assign p_40_44_s_60_fu_1131_p2 = (tmp7_fu_1126_p2 & p_40_1_58_reg_1568);

assign p_40_44_s_fu_1004_p2 = (tmp_3_24_reg_1461_pp0_iter2_reg & p_40_1_58_fu_1000_p2);

assign p_40_46_s_fu_1140_p2 = (tmp_3_28_reg_1483_pp0_iter3_reg & p_40_2_fu_1136_p2);

assign p_40_s_51_fu_816_p2 = (tmp_3_16_reg_1417_pp0_iter1_reg & p_40_s_fu_811_p2);

assign p_40_s_52_fu_821_p2 = (tmp_3_17_reg_1423_pp0_iter1_reg & p_40_s_51_fu_816_p2);

assign p_40_s_53_fu_945_p2 = (tmp_3_18_reg_1429_pp0_iter2_reg & p_40_s_52_reg_1546);

assign p_40_s_54_fu_959_p2 = (tmp5_fu_954_p2 & p_40_s_51_reg_1540);

assign p_40_s_55_fu_969_p2 = (p_40_s_reg_1534 & not_tmp_3_8_fu_964_p2);

assign p_40_s_56_fu_994_p2 = (tmp6_fu_989_p2 & p_40_s_55_fu_969_p2);

assign p_40_s_61_fu_1233_p2 = (tmp8_fu_1228_p2 & p_3_reg_1580_pp0_iter4_reg);

assign p_40_s_fu_811_p2 = (tmp_3_15_reg_1411_pp0_iter1_reg & not_tmp_3_fu_806_p2);

assign p_s_41_fu_572_p2 = (tmp_3_2_fu_392_p2 & p_s_fu_566_p2);

assign p_s_42_fu_578_p2 = (tmp_3_3_reg_1341 & p_s_41_reg_1502);

assign p_s_43_fu_582_p2 = (tmp_3_4_reg_1347 & p_s_42_fu_578_p2);

assign p_s_fu_566_p2 = (tmp_3_fu_380_p2 & tmp_3_1_fu_386_p2);

assign tmp1_fu_592_p2 = (tmp_3_7_reg_1352 & not_tmp_3_3_fu_587_p2);

assign tmp2_fu_627_p2 = (tmp_3_6_reg_1368 & not_tmp_3_s_fu_622_p2);

assign tmp3_fu_772_p2 = (tmp_3_11_reg_1390_pp0_iter1_reg & not_tmp_3_4_fu_767_p2);

assign tmp4_fu_796_p2 = (tmp_3_14_reg_1406_pp0_iter1_reg & not_tmp_3_6_fu_791_p2);

assign tmp5_fu_954_p2 = (tmp_3_19_reg_1434_pp0_iter2_reg & not_tmp_3_7_fu_949_p2);

assign tmp6_fu_989_p2 = (tmp_3_22_reg_1450_pp0_iter2_reg & not_tmp_3_9_fu_984_p2);

assign tmp7_fu_1126_p2 = (tmp_3_26_reg_1472_pp0_iter3_reg & not_tmp_3_11_fu_1121_p2);

assign tmp8_fu_1228_p2 = (tmp_3_29_reg_1488_pp0_iter4_reg & not_tmp_3_13_fu_1223_p2);

assign tmp_10_fu_894_p3 = ((brmerge6_fu_846_p2[0:0] === 1'b1) ? tmp_s_fu_886_p3 : 4'd11);

assign tmp_11_fu_902_p3 = ((brmerge7_fu_852_p2[0:0] === 1'b1) ? tmp_10_fu_894_p3 : 4'd12);

assign tmp_12_fu_910_p3 = ((brmerge8_fu_856_p2[0:0] === 1'b1) ? tmp_11_fu_902_p3 : 4'd13);

assign tmp_13_fu_918_p3 = ((brmerge9_fu_862_p2[0:0] === 1'b1) ? tmp_12_fu_910_p3 : 4'd14);

assign tmp_14_cast_fu_934_p1 = tmp_14_fu_926_p3;

assign tmp_14_fu_926_p3 = ((brmerge10_fu_868_p2[0:0] === 1'b1) ? tmp_13_fu_918_p3 : 4'd15);

assign tmp_15_fu_938_p3 = ((tmp_3_reg_1320_pp0_iter1_reg[0:0] === 1'b1) ? tmp_14_cast_fu_934_p1 : 5'd16);

assign tmp_16_fu_1055_p3 = ((brmerge11_fu_1019_p2[0:0] === 1'b1) ? tmp_15_reg_1563 : 5'd17);

assign tmp_17_fu_1062_p3 = ((brmerge12_reg_1557[0:0] === 1'b1) ? tmp_16_fu_1055_p3 : 5'd18);

assign tmp_18_fu_1069_p3 = ((brmerge13_fu_1024_p2[0:0] === 1'b1) ? tmp_17_fu_1062_p3 : 5'd19);

assign tmp_19_fu_1077_p3 = ((brmerge14_fu_1029_p2[0:0] === 1'b1) ? tmp_18_fu_1069_p3 : 5'd20);

assign tmp_1_fu_701_p3 = ((p_s_42_fu_578_p2[0:0] === 1'b1) ? tmp_cast_fu_697_p1 : 2'd2);

assign tmp_20_fu_1085_p3 = ((brmerge15_fu_1033_p2[0:0] === 1'b1) ? tmp_19_fu_1077_p3 : 5'd21);

assign tmp_21_fu_1093_p3 = ((brmerge16_fu_1039_p2[0:0] === 1'b1) ? tmp_20_fu_1085_p3 : 5'd22);

assign tmp_22_fu_1101_p3 = ((brmerge17_fu_1045_p2[0:0] === 1'b1) ? tmp_21_fu_1093_p3 : 5'd23);

assign tmp_23_fu_1109_p3 = ((brmerge18_fu_1051_p2[0:0] === 1'b1) ? tmp_22_fu_1101_p3 : 5'd24);

assign tmp_24_fu_1176_p3 = ((brmerge19_fu_1145_p2[0:0] === 1'b1) ? tmp_23_reg_1593 : 5'd25);

assign tmp_25_fu_1183_p3 = ((brmerge20_fu_1150_p2[0:0] === 1'b1) ? tmp_24_fu_1176_p3 : 5'd26);

assign tmp_26_fu_1191_p3 = ((brmerge21_fu_1154_p2[0:0] === 1'b1) ? tmp_25_fu_1183_p3 : 5'd27);

assign tmp_27_fu_1199_p3 = ((brmerge22_fu_1160_p2[0:0] === 1'b1) ? tmp_26_fu_1191_p3 : 5'd28);

assign tmp_28_fu_1207_p3 = ((brmerge23_fu_1164_p2[0:0] === 1'b1) ? tmp_27_fu_1199_p3 : 5'd29);

assign tmp_29_fu_1215_p3 = ((brmerge24_fu_1170_p2[0:0] === 1'b1) ? tmp_28_fu_1207_p3 : 5'd30);

assign tmp_2_cast_fu_717_p1 = tmp_2_fu_709_p3;

assign tmp_2_fu_709_p3 = ((brmerge_fu_669_p2[0:0] === 1'b1) ? tmp_1_fu_701_p3 : 2'd3);

assign tmp_3_10_fu_446_p2 = (($signed(x_542_V_read_int_reg) < $signed(18'd17409)) ? 1'b1 : 1'b0);

assign tmp_3_11_fu_452_p2 = (($signed(x_578_V_read_int_reg) < $signed(18'd3585)) ? 1'b1 : 1'b0);

assign tmp_3_12_fu_458_p2 = (($signed(x_487_V_read_int_reg) < $signed(18'd8705)) ? 1'b1 : 1'b0);

assign tmp_3_13_fu_464_p2 = (($signed(x_383_V_read_int_reg) < $signed(18'd130561)) ? 1'b1 : 1'b0);

assign tmp_3_14_fu_470_p2 = (($signed(x_347_V_read_int_reg) < $signed(18'd513)) ? 1'b1 : 1'b0);

assign tmp_3_15_fu_476_p2 = (($signed(x_461_V_read_int_reg) < $signed(18'd513)) ? 1'b1 : 1'b0);

assign tmp_3_16_fu_482_p2 = (($signed(x_454_V_read_int_reg) < $signed(18'd10753)) ? 1'b1 : 1'b0);

assign tmp_3_17_fu_488_p2 = (($signed(x_408_V_read_int_reg) < $signed(18'd513)) ? 1'b1 : 1'b0);

assign tmp_3_18_fu_494_p2 = (($signed(x_288_V_read_int_reg) < $signed(18'd212993)) ? 1'b1 : 1'b0);

assign tmp_3_19_fu_500_p2 = (($signed(x_155_V_read_int_reg) < $signed(18'd513)) ? 1'b1 : 1'b0);

assign tmp_3_1_fu_386_p2 = (($signed(x_466_V_read_int_reg) < $signed(18'd513)) ? 1'b1 : 1'b0);

assign tmp_3_20_fu_506_p2 = (($signed(x_435_V_read_int_reg) < $signed(18'd513)) ? 1'b1 : 1'b0);

assign tmp_3_21_fu_512_p2 = (($signed(x_598_V_read_int_reg) < $signed(18'd6145)) ? 1'b1 : 1'b0);

assign tmp_3_22_fu_518_p2 = (($signed(x_327_V_read_int_reg) < $signed(18'd3585)) ? 1'b1 : 1'b0);

assign tmp_3_23_fu_524_p2 = (($signed(x_655_V_read_int_reg) < $signed(18'd1537)) ? 1'b1 : 1'b0);

assign tmp_3_24_fu_530_p2 = (($signed(x_99_V_read_int_reg) < $signed(18'd513)) ? 1'b1 : 1'b0);

assign tmp_3_25_fu_536_p2 = (($signed(x_210_V_read_int_reg) < $signed(18'd3585)) ? 1'b1 : 1'b0);

assign tmp_3_26_fu_542_p2 = (($signed(x_591_V_read_int_reg) < $signed(18'd65537)) ? 1'b1 : 1'b0);

assign tmp_3_27_fu_548_p2 = (($signed(x_660_V_read_int_reg) < $signed(18'd513)) ? 1'b1 : 1'b0);

assign tmp_3_28_fu_554_p2 = (($signed(x_157_V_read_int_reg) < $signed(18'd16897)) ? 1'b1 : 1'b0);

assign tmp_3_29_fu_560_p2 = (($signed(x_154_V_read_int_reg) < $signed(18'd7681)) ? 1'b1 : 1'b0);

assign tmp_3_2_fu_392_p2 = (($signed(x_524_V_read_int_reg) < $signed(18'd1025)) ? 1'b1 : 1'b0);

assign tmp_3_3_fu_398_p2 = (($signed(x_378_V_read_int_reg) < $signed(18'd143873)) ? 1'b1 : 1'b0);

assign tmp_3_4_fu_404_p2 = (($signed(x_636_V_read_int_reg) < $signed(18'd513)) ? 1'b1 : 1'b0);

assign tmp_3_5_fu_422_p2 = (($signed(x_660_V_read_int_reg) < $signed(18'd1025)) ? 1'b1 : 1'b0);

assign tmp_3_6_fu_428_p2 = (($signed(x_516_V_read_int_reg) < $signed(18'd2049)) ? 1'b1 : 1'b0);

assign tmp_3_7_fu_410_p2 = (($signed(x_205_V_read_int_reg) < $signed(18'd513)) ? 1'b1 : 1'b0);

assign tmp_3_8_fu_434_p2 = (($signed(x_154_V_read_int_reg) < $signed(18'd513)) ? 1'b1 : 1'b0);

assign tmp_3_9_fu_440_p2 = (($signed(x_236_V_read_int_reg) < $signed(18'd18945)) ? 1'b1 : 1'b0);

assign tmp_3_fu_380_p2 = (($signed(x_318_V_read_int_reg) < $signed(18'd513)) ? 1'b1 : 1'b0);

assign tmp_3_s_fu_416_p2 = (($signed(x_398_V_read_int_reg) < $signed(18'd12801)) ? 1'b1 : 1'b0);

assign tmp_4_fu_721_p3 = ((p_s_41_reg_1502[0:0] === 1'b1) ? tmp_2_cast_fu_717_p1 : 3'd4);

assign tmp_5_fu_728_p3 = ((brmerge1_fu_675_p2[0:0] === 1'b1) ? tmp_4_fu_721_p3 : 3'd5);

assign tmp_6_fu_736_p3 = ((brmerge2_fu_680_p2[0:0] === 1'b1) ? tmp_5_fu_728_p3 : 3'd6);

assign tmp_7_cast_fu_752_p1 = tmp_7_fu_744_p3;

assign tmp_7_fu_744_p3 = ((brmerge3_fu_685_p2[0:0] === 1'b1) ? tmp_6_fu_736_p3 : 3'd7);

assign tmp_8_fu_756_p3 = ((p_s_reg_1493[0:0] === 1'b1) ? tmp_7_cast_fu_752_p1 : 4'd8);

assign tmp_9_fu_879_p3 = ((brmerge4_fu_837_p2[0:0] === 1'b1) ? tmp_8_reg_1529 : 4'd9);

assign tmp_cast_fu_697_p1 = not_s_fu_691_p2;

assign tmp_fu_1250_p33 = ((brmerge25_fu_1238_p2[0:0] === 1'b1) ? tmp_29_reg_1603 : 5'd31);

assign tmp_s_fu_886_p3 = ((brmerge5_fu_842_p2[0:0] === 1'b1) ? tmp_9_fu_879_p3 : 4'd10);

endmodule //decision_function
