// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="my_prj,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7a200tfbg676-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.372000,HLS_SYN_LAT=7,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4823,HLS_SYN_LUT=4528,HLS_VERSION=2018_3}" *)

module my_prj (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_0_V,
        x_1_V,
        x_2_V,
        x_3_V,
        x_4_V,
        x_5_V,
        x_6_V,
        x_7_V,
        x_8_V,
        x_9_V,
        x_10_V,
        x_11_V,
        x_12_V,
        x_13_V,
        x_14_V,
        x_15_V,
        x_16_V,
        x_17_V,
        x_18_V,
        x_19_V,
        x_20_V,
        x_21_V,
        x_22_V,
        x_23_V,
        x_24_V,
        x_25_V,
        x_26_V,
        x_27_V,
        x_28_V,
        x_29_V,
        x_30_V,
        x_31_V,
        x_32_V,
        x_33_V,
        x_34_V,
        x_35_V,
        x_36_V,
        x_37_V,
        x_38_V,
        x_39_V,
        x_40_V,
        x_41_V,
        x_42_V,
        x_43_V,
        x_44_V,
        x_45_V,
        x_46_V,
        x_47_V,
        x_48_V,
        x_49_V,
        x_50_V,
        x_51_V,
        x_52_V,
        x_53_V,
        x_54_V,
        x_55_V,
        x_56_V,
        x_57_V,
        x_58_V,
        x_59_V,
        x_60_V,
        x_61_V,
        x_62_V,
        x_63_V,
        x_64_V,
        x_65_V,
        x_66_V,
        x_67_V,
        x_68_V,
        x_69_V,
        x_70_V,
        x_71_V,
        x_72_V,
        x_73_V,
        x_74_V,
        x_75_V,
        x_76_V,
        x_77_V,
        x_78_V,
        x_79_V,
        x_80_V,
        x_81_V,
        x_82_V,
        x_83_V,
        x_84_V,
        x_85_V,
        x_86_V,
        x_87_V,
        x_88_V,
        x_89_V,
        x_90_V,
        x_91_V,
        x_92_V,
        x_93_V,
        x_94_V,
        x_95_V,
        x_96_V,
        x_97_V,
        x_98_V,
        x_99_V,
        x_100_V,
        x_101_V,
        x_102_V,
        x_103_V,
        x_104_V,
        x_105_V,
        x_106_V,
        x_107_V,
        x_108_V,
        x_109_V,
        x_110_V,
        x_111_V,
        x_112_V,
        x_113_V,
        x_114_V,
        x_115_V,
        x_116_V,
        x_117_V,
        x_118_V,
        x_119_V,
        x_120_V,
        x_121_V,
        x_122_V,
        x_123_V,
        x_124_V,
        x_125_V,
        x_126_V,
        x_127_V,
        x_128_V,
        x_129_V,
        x_130_V,
        x_131_V,
        x_132_V,
        x_133_V,
        x_134_V,
        x_135_V,
        x_136_V,
        x_137_V,
        x_138_V,
        x_139_V,
        x_140_V,
        x_141_V,
        x_142_V,
        x_143_V,
        x_144_V,
        x_145_V,
        x_146_V,
        x_147_V,
        x_148_V,
        x_149_V,
        x_150_V,
        x_151_V,
        x_152_V,
        x_153_V,
        x_154_V,
        x_155_V,
        x_156_V,
        x_157_V,
        x_158_V,
        x_159_V,
        x_160_V,
        x_161_V,
        x_162_V,
        x_163_V,
        x_164_V,
        x_165_V,
        x_166_V,
        x_167_V,
        x_168_V,
        x_169_V,
        x_170_V,
        x_171_V,
        x_172_V,
        x_173_V,
        x_174_V,
        x_175_V,
        x_176_V,
        x_177_V,
        x_178_V,
        x_179_V,
        x_180_V,
        x_181_V,
        x_182_V,
        x_183_V,
        x_184_V,
        x_185_V,
        x_186_V,
        x_187_V,
        x_188_V,
        x_189_V,
        x_190_V,
        x_191_V,
        x_192_V,
        x_193_V,
        x_194_V,
        x_195_V,
        x_196_V,
        x_197_V,
        x_198_V,
        x_199_V,
        x_200_V,
        x_201_V,
        x_202_V,
        x_203_V,
        x_204_V,
        x_205_V,
        x_206_V,
        x_207_V,
        x_208_V,
        x_209_V,
        x_210_V,
        x_211_V,
        x_212_V,
        x_213_V,
        x_214_V,
        x_215_V,
        x_216_V,
        x_217_V,
        x_218_V,
        x_219_V,
        x_220_V,
        x_221_V,
        x_222_V,
        x_223_V,
        x_224_V,
        x_225_V,
        x_226_V,
        x_227_V,
        x_228_V,
        x_229_V,
        x_230_V,
        x_231_V,
        x_232_V,
        x_233_V,
        x_234_V,
        x_235_V,
        x_236_V,
        x_237_V,
        x_238_V,
        x_239_V,
        x_240_V,
        x_241_V,
        x_242_V,
        x_243_V,
        x_244_V,
        x_245_V,
        x_246_V,
        x_247_V,
        x_248_V,
        x_249_V,
        x_250_V,
        x_251_V,
        x_252_V,
        x_253_V,
        x_254_V,
        x_255_V,
        x_256_V,
        x_257_V,
        x_258_V,
        x_259_V,
        x_260_V,
        x_261_V,
        x_262_V,
        x_263_V,
        x_264_V,
        x_265_V,
        x_266_V,
        x_267_V,
        x_268_V,
        x_269_V,
        x_270_V,
        x_271_V,
        x_272_V,
        x_273_V,
        x_274_V,
        x_275_V,
        x_276_V,
        x_277_V,
        x_278_V,
        x_279_V,
        x_280_V,
        x_281_V,
        x_282_V,
        x_283_V,
        x_284_V,
        x_285_V,
        x_286_V,
        x_287_V,
        x_288_V,
        x_289_V,
        x_290_V,
        x_291_V,
        x_292_V,
        x_293_V,
        x_294_V,
        x_295_V,
        x_296_V,
        x_297_V,
        x_298_V,
        x_299_V,
        x_300_V,
        x_301_V,
        x_302_V,
        x_303_V,
        x_304_V,
        x_305_V,
        x_306_V,
        x_307_V,
        x_308_V,
        x_309_V,
        x_310_V,
        x_311_V,
        x_312_V,
        x_313_V,
        x_314_V,
        x_315_V,
        x_316_V,
        x_317_V,
        x_318_V,
        x_319_V,
        x_320_V,
        x_321_V,
        x_322_V,
        x_323_V,
        x_324_V,
        x_325_V,
        x_326_V,
        x_327_V,
        x_328_V,
        x_329_V,
        x_330_V,
        x_331_V,
        x_332_V,
        x_333_V,
        x_334_V,
        x_335_V,
        x_336_V,
        x_337_V,
        x_338_V,
        x_339_V,
        x_340_V,
        x_341_V,
        x_342_V,
        x_343_V,
        x_344_V,
        x_345_V,
        x_346_V,
        x_347_V,
        x_348_V,
        x_349_V,
        x_350_V,
        x_351_V,
        x_352_V,
        x_353_V,
        x_354_V,
        x_355_V,
        x_356_V,
        x_357_V,
        x_358_V,
        x_359_V,
        x_360_V,
        x_361_V,
        x_362_V,
        x_363_V,
        x_364_V,
        x_365_V,
        x_366_V,
        x_367_V,
        x_368_V,
        x_369_V,
        x_370_V,
        x_371_V,
        x_372_V,
        x_373_V,
        x_374_V,
        x_375_V,
        x_376_V,
        x_377_V,
        x_378_V,
        x_379_V,
        x_380_V,
        x_381_V,
        x_382_V,
        x_383_V,
        x_384_V,
        x_385_V,
        x_386_V,
        x_387_V,
        x_388_V,
        x_389_V,
        x_390_V,
        x_391_V,
        x_392_V,
        x_393_V,
        x_394_V,
        x_395_V,
        x_396_V,
        x_397_V,
        x_398_V,
        x_399_V,
        x_400_V,
        x_401_V,
        x_402_V,
        x_403_V,
        x_404_V,
        x_405_V,
        x_406_V,
        x_407_V,
        x_408_V,
        x_409_V,
        x_410_V,
        x_411_V,
        x_412_V,
        x_413_V,
        x_414_V,
        x_415_V,
        x_416_V,
        x_417_V,
        x_418_V,
        x_419_V,
        x_420_V,
        x_421_V,
        x_422_V,
        x_423_V,
        x_424_V,
        x_425_V,
        x_426_V,
        x_427_V,
        x_428_V,
        x_429_V,
        x_430_V,
        x_431_V,
        x_432_V,
        x_433_V,
        x_434_V,
        x_435_V,
        x_436_V,
        x_437_V,
        x_438_V,
        x_439_V,
        x_440_V,
        x_441_V,
        x_442_V,
        x_443_V,
        x_444_V,
        x_445_V,
        x_446_V,
        x_447_V,
        x_448_V,
        x_449_V,
        x_450_V,
        x_451_V,
        x_452_V,
        x_453_V,
        x_454_V,
        x_455_V,
        x_456_V,
        x_457_V,
        x_458_V,
        x_459_V,
        x_460_V,
        x_461_V,
        x_462_V,
        x_463_V,
        x_464_V,
        x_465_V,
        x_466_V,
        x_467_V,
        x_468_V,
        x_469_V,
        x_470_V,
        x_471_V,
        x_472_V,
        x_473_V,
        x_474_V,
        x_475_V,
        x_476_V,
        x_477_V,
        x_478_V,
        x_479_V,
        x_480_V,
        x_481_V,
        x_482_V,
        x_483_V,
        x_484_V,
        x_485_V,
        x_486_V,
        x_487_V,
        x_488_V,
        x_489_V,
        x_490_V,
        x_491_V,
        x_492_V,
        x_493_V,
        x_494_V,
        x_495_V,
        x_496_V,
        x_497_V,
        x_498_V,
        x_499_V,
        x_500_V,
        x_501_V,
        x_502_V,
        x_503_V,
        x_504_V,
        x_505_V,
        x_506_V,
        x_507_V,
        x_508_V,
        x_509_V,
        x_510_V,
        x_511_V,
        x_512_V,
        x_513_V,
        x_514_V,
        x_515_V,
        x_516_V,
        x_517_V,
        x_518_V,
        x_519_V,
        x_520_V,
        x_521_V,
        x_522_V,
        x_523_V,
        x_524_V,
        x_525_V,
        x_526_V,
        x_527_V,
        x_528_V,
        x_529_V,
        x_530_V,
        x_531_V,
        x_532_V,
        x_533_V,
        x_534_V,
        x_535_V,
        x_536_V,
        x_537_V,
        x_538_V,
        x_539_V,
        x_540_V,
        x_541_V,
        x_542_V,
        x_543_V,
        x_544_V,
        x_545_V,
        x_546_V,
        x_547_V,
        x_548_V,
        x_549_V,
        x_550_V,
        x_551_V,
        x_552_V,
        x_553_V,
        x_554_V,
        x_555_V,
        x_556_V,
        x_557_V,
        x_558_V,
        x_559_V,
        x_560_V,
        x_561_V,
        x_562_V,
        x_563_V,
        x_564_V,
        x_565_V,
        x_566_V,
        x_567_V,
        x_568_V,
        x_569_V,
        x_570_V,
        x_571_V,
        x_572_V,
        x_573_V,
        x_574_V,
        x_575_V,
        x_576_V,
        x_577_V,
        x_578_V,
        x_579_V,
        x_580_V,
        x_581_V,
        x_582_V,
        x_583_V,
        x_584_V,
        x_585_V,
        x_586_V,
        x_587_V,
        x_588_V,
        x_589_V,
        x_590_V,
        x_591_V,
        x_592_V,
        x_593_V,
        x_594_V,
        x_595_V,
        x_596_V,
        x_597_V,
        x_598_V,
        x_599_V,
        x_600_V,
        x_601_V,
        x_602_V,
        x_603_V,
        x_604_V,
        x_605_V,
        x_606_V,
        x_607_V,
        x_608_V,
        x_609_V,
        x_610_V,
        x_611_V,
        x_612_V,
        x_613_V,
        x_614_V,
        x_615_V,
        x_616_V,
        x_617_V,
        x_618_V,
        x_619_V,
        x_620_V,
        x_621_V,
        x_622_V,
        x_623_V,
        x_624_V,
        x_625_V,
        x_626_V,
        x_627_V,
        x_628_V,
        x_629_V,
        x_630_V,
        x_631_V,
        x_632_V,
        x_633_V,
        x_634_V,
        x_635_V,
        x_636_V,
        x_637_V,
        x_638_V,
        x_639_V,
        x_640_V,
        x_641_V,
        x_642_V,
        x_643_V,
        x_644_V,
        x_645_V,
        x_646_V,
        x_647_V,
        x_648_V,
        x_649_V,
        x_650_V,
        x_651_V,
        x_652_V,
        x_653_V,
        x_654_V,
        x_655_V,
        x_656_V,
        x_657_V,
        x_658_V,
        x_659_V,
        x_660_V,
        x_661_V,
        x_662_V,
        x_663_V,
        x_664_V,
        x_665_V,
        x_666_V,
        x_667_V,
        x_668_V,
        x_669_V,
        x_670_V,
        x_671_V,
        x_672_V,
        x_673_V,
        x_674_V,
        x_675_V,
        x_676_V,
        x_677_V,
        x_678_V,
        x_679_V,
        x_680_V,
        x_681_V,
        x_682_V,
        x_683_V,
        x_684_V,
        x_685_V,
        x_686_V,
        x_687_V,
        x_688_V,
        x_689_V,
        x_690_V,
        x_691_V,
        x_692_V,
        x_693_V,
        x_694_V,
        x_695_V,
        x_696_V,
        x_697_V,
        x_698_V,
        x_699_V,
        x_700_V,
        x_701_V,
        x_702_V,
        x_703_V,
        x_704_V,
        x_705_V,
        x_706_V,
        x_707_V,
        x_708_V,
        x_709_V,
        x_710_V,
        x_711_V,
        x_712_V,
        x_713_V,
        x_714_V,
        x_715_V,
        x_716_V,
        x_717_V,
        x_718_V,
        x_719_V,
        x_720_V,
        x_721_V,
        x_722_V,
        x_723_V,
        x_724_V,
        x_725_V,
        x_726_V,
        x_727_V,
        x_728_V,
        x_729_V,
        x_730_V,
        x_731_V,
        x_732_V,
        x_733_V,
        x_734_V,
        x_735_V,
        x_736_V,
        x_737_V,
        x_738_V,
        x_739_V,
        x_740_V,
        x_741_V,
        x_742_V,
        x_743_V,
        x_744_V,
        x_745_V,
        x_746_V,
        x_747_V,
        x_748_V,
        x_749_V,
        x_750_V,
        x_751_V,
        x_752_V,
        x_753_V,
        x_754_V,
        x_755_V,
        x_756_V,
        x_757_V,
        x_758_V,
        x_759_V,
        x_760_V,
        x_761_V,
        x_762_V,
        x_763_V,
        x_764_V,
        x_765_V,
        x_766_V,
        x_767_V,
        x_768_V,
        x_769_V,
        x_770_V,
        x_771_V,
        x_772_V,
        x_773_V,
        x_774_V,
        x_775_V,
        x_776_V,
        x_777_V,
        x_778_V,
        x_779_V,
        x_780_V,
        x_781_V,
        x_782_V,
        x_783_V,
        score_0_V,
        score_0_V_ap_vld,
        score_1_V,
        score_2_V,
        score_3_V,
        score_4_V,
        score_5_V,
        score_6_V,
        score_7_V,
        score_8_V,
        score_9_V
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [17:0] x_0_V;
input  [17:0] x_1_V;
input  [17:0] x_2_V;
input  [17:0] x_3_V;
input  [17:0] x_4_V;
input  [17:0] x_5_V;
input  [17:0] x_6_V;
input  [17:0] x_7_V;
input  [17:0] x_8_V;
input  [17:0] x_9_V;
input  [17:0] x_10_V;
input  [17:0] x_11_V;
input  [17:0] x_12_V;
input  [17:0] x_13_V;
input  [17:0] x_14_V;
input  [17:0] x_15_V;
input  [17:0] x_16_V;
input  [17:0] x_17_V;
input  [17:0] x_18_V;
input  [17:0] x_19_V;
input  [17:0] x_20_V;
input  [17:0] x_21_V;
input  [17:0] x_22_V;
input  [17:0] x_23_V;
input  [17:0] x_24_V;
input  [17:0] x_25_V;
input  [17:0] x_26_V;
input  [17:0] x_27_V;
input  [17:0] x_28_V;
input  [17:0] x_29_V;
input  [17:0] x_30_V;
input  [17:0] x_31_V;
input  [17:0] x_32_V;
input  [17:0] x_33_V;
input  [17:0] x_34_V;
input  [17:0] x_35_V;
input  [17:0] x_36_V;
input  [17:0] x_37_V;
input  [17:0] x_38_V;
input  [17:0] x_39_V;
input  [17:0] x_40_V;
input  [17:0] x_41_V;
input  [17:0] x_42_V;
input  [17:0] x_43_V;
input  [17:0] x_44_V;
input  [17:0] x_45_V;
input  [17:0] x_46_V;
input  [17:0] x_47_V;
input  [17:0] x_48_V;
input  [17:0] x_49_V;
input  [17:0] x_50_V;
input  [17:0] x_51_V;
input  [17:0] x_52_V;
input  [17:0] x_53_V;
input  [17:0] x_54_V;
input  [17:0] x_55_V;
input  [17:0] x_56_V;
input  [17:0] x_57_V;
input  [17:0] x_58_V;
input  [17:0] x_59_V;
input  [17:0] x_60_V;
input  [17:0] x_61_V;
input  [17:0] x_62_V;
input  [17:0] x_63_V;
input  [17:0] x_64_V;
input  [17:0] x_65_V;
input  [17:0] x_66_V;
input  [17:0] x_67_V;
input  [17:0] x_68_V;
input  [17:0] x_69_V;
input  [17:0] x_70_V;
input  [17:0] x_71_V;
input  [17:0] x_72_V;
input  [17:0] x_73_V;
input  [17:0] x_74_V;
input  [17:0] x_75_V;
input  [17:0] x_76_V;
input  [17:0] x_77_V;
input  [17:0] x_78_V;
input  [17:0] x_79_V;
input  [17:0] x_80_V;
input  [17:0] x_81_V;
input  [17:0] x_82_V;
input  [17:0] x_83_V;
input  [17:0] x_84_V;
input  [17:0] x_85_V;
input  [17:0] x_86_V;
input  [17:0] x_87_V;
input  [17:0] x_88_V;
input  [17:0] x_89_V;
input  [17:0] x_90_V;
input  [17:0] x_91_V;
input  [17:0] x_92_V;
input  [17:0] x_93_V;
input  [17:0] x_94_V;
input  [17:0] x_95_V;
input  [17:0] x_96_V;
input  [17:0] x_97_V;
input  [17:0] x_98_V;
input  [17:0] x_99_V;
input  [17:0] x_100_V;
input  [17:0] x_101_V;
input  [17:0] x_102_V;
input  [17:0] x_103_V;
input  [17:0] x_104_V;
input  [17:0] x_105_V;
input  [17:0] x_106_V;
input  [17:0] x_107_V;
input  [17:0] x_108_V;
input  [17:0] x_109_V;
input  [17:0] x_110_V;
input  [17:0] x_111_V;
input  [17:0] x_112_V;
input  [17:0] x_113_V;
input  [17:0] x_114_V;
input  [17:0] x_115_V;
input  [17:0] x_116_V;
input  [17:0] x_117_V;
input  [17:0] x_118_V;
input  [17:0] x_119_V;
input  [17:0] x_120_V;
input  [17:0] x_121_V;
input  [17:0] x_122_V;
input  [17:0] x_123_V;
input  [17:0] x_124_V;
input  [17:0] x_125_V;
input  [17:0] x_126_V;
input  [17:0] x_127_V;
input  [17:0] x_128_V;
input  [17:0] x_129_V;
input  [17:0] x_130_V;
input  [17:0] x_131_V;
input  [17:0] x_132_V;
input  [17:0] x_133_V;
input  [17:0] x_134_V;
input  [17:0] x_135_V;
input  [17:0] x_136_V;
input  [17:0] x_137_V;
input  [17:0] x_138_V;
input  [17:0] x_139_V;
input  [17:0] x_140_V;
input  [17:0] x_141_V;
input  [17:0] x_142_V;
input  [17:0] x_143_V;
input  [17:0] x_144_V;
input  [17:0] x_145_V;
input  [17:0] x_146_V;
input  [17:0] x_147_V;
input  [17:0] x_148_V;
input  [17:0] x_149_V;
input  [17:0] x_150_V;
input  [17:0] x_151_V;
input  [17:0] x_152_V;
input  [17:0] x_153_V;
input  [17:0] x_154_V;
input  [17:0] x_155_V;
input  [17:0] x_156_V;
input  [17:0] x_157_V;
input  [17:0] x_158_V;
input  [17:0] x_159_V;
input  [17:0] x_160_V;
input  [17:0] x_161_V;
input  [17:0] x_162_V;
input  [17:0] x_163_V;
input  [17:0] x_164_V;
input  [17:0] x_165_V;
input  [17:0] x_166_V;
input  [17:0] x_167_V;
input  [17:0] x_168_V;
input  [17:0] x_169_V;
input  [17:0] x_170_V;
input  [17:0] x_171_V;
input  [17:0] x_172_V;
input  [17:0] x_173_V;
input  [17:0] x_174_V;
input  [17:0] x_175_V;
input  [17:0] x_176_V;
input  [17:0] x_177_V;
input  [17:0] x_178_V;
input  [17:0] x_179_V;
input  [17:0] x_180_V;
input  [17:0] x_181_V;
input  [17:0] x_182_V;
input  [17:0] x_183_V;
input  [17:0] x_184_V;
input  [17:0] x_185_V;
input  [17:0] x_186_V;
input  [17:0] x_187_V;
input  [17:0] x_188_V;
input  [17:0] x_189_V;
input  [17:0] x_190_V;
input  [17:0] x_191_V;
input  [17:0] x_192_V;
input  [17:0] x_193_V;
input  [17:0] x_194_V;
input  [17:0] x_195_V;
input  [17:0] x_196_V;
input  [17:0] x_197_V;
input  [17:0] x_198_V;
input  [17:0] x_199_V;
input  [17:0] x_200_V;
input  [17:0] x_201_V;
input  [17:0] x_202_V;
input  [17:0] x_203_V;
input  [17:0] x_204_V;
input  [17:0] x_205_V;
input  [17:0] x_206_V;
input  [17:0] x_207_V;
input  [17:0] x_208_V;
input  [17:0] x_209_V;
input  [17:0] x_210_V;
input  [17:0] x_211_V;
input  [17:0] x_212_V;
input  [17:0] x_213_V;
input  [17:0] x_214_V;
input  [17:0] x_215_V;
input  [17:0] x_216_V;
input  [17:0] x_217_V;
input  [17:0] x_218_V;
input  [17:0] x_219_V;
input  [17:0] x_220_V;
input  [17:0] x_221_V;
input  [17:0] x_222_V;
input  [17:0] x_223_V;
input  [17:0] x_224_V;
input  [17:0] x_225_V;
input  [17:0] x_226_V;
input  [17:0] x_227_V;
input  [17:0] x_228_V;
input  [17:0] x_229_V;
input  [17:0] x_230_V;
input  [17:0] x_231_V;
input  [17:0] x_232_V;
input  [17:0] x_233_V;
input  [17:0] x_234_V;
input  [17:0] x_235_V;
input  [17:0] x_236_V;
input  [17:0] x_237_V;
input  [17:0] x_238_V;
input  [17:0] x_239_V;
input  [17:0] x_240_V;
input  [17:0] x_241_V;
input  [17:0] x_242_V;
input  [17:0] x_243_V;
input  [17:0] x_244_V;
input  [17:0] x_245_V;
input  [17:0] x_246_V;
input  [17:0] x_247_V;
input  [17:0] x_248_V;
input  [17:0] x_249_V;
input  [17:0] x_250_V;
input  [17:0] x_251_V;
input  [17:0] x_252_V;
input  [17:0] x_253_V;
input  [17:0] x_254_V;
input  [17:0] x_255_V;
input  [17:0] x_256_V;
input  [17:0] x_257_V;
input  [17:0] x_258_V;
input  [17:0] x_259_V;
input  [17:0] x_260_V;
input  [17:0] x_261_V;
input  [17:0] x_262_V;
input  [17:0] x_263_V;
input  [17:0] x_264_V;
input  [17:0] x_265_V;
input  [17:0] x_266_V;
input  [17:0] x_267_V;
input  [17:0] x_268_V;
input  [17:0] x_269_V;
input  [17:0] x_270_V;
input  [17:0] x_271_V;
input  [17:0] x_272_V;
input  [17:0] x_273_V;
input  [17:0] x_274_V;
input  [17:0] x_275_V;
input  [17:0] x_276_V;
input  [17:0] x_277_V;
input  [17:0] x_278_V;
input  [17:0] x_279_V;
input  [17:0] x_280_V;
input  [17:0] x_281_V;
input  [17:0] x_282_V;
input  [17:0] x_283_V;
input  [17:0] x_284_V;
input  [17:0] x_285_V;
input  [17:0] x_286_V;
input  [17:0] x_287_V;
input  [17:0] x_288_V;
input  [17:0] x_289_V;
input  [17:0] x_290_V;
input  [17:0] x_291_V;
input  [17:0] x_292_V;
input  [17:0] x_293_V;
input  [17:0] x_294_V;
input  [17:0] x_295_V;
input  [17:0] x_296_V;
input  [17:0] x_297_V;
input  [17:0] x_298_V;
input  [17:0] x_299_V;
input  [17:0] x_300_V;
input  [17:0] x_301_V;
input  [17:0] x_302_V;
input  [17:0] x_303_V;
input  [17:0] x_304_V;
input  [17:0] x_305_V;
input  [17:0] x_306_V;
input  [17:0] x_307_V;
input  [17:0] x_308_V;
input  [17:0] x_309_V;
input  [17:0] x_310_V;
input  [17:0] x_311_V;
input  [17:0] x_312_V;
input  [17:0] x_313_V;
input  [17:0] x_314_V;
input  [17:0] x_315_V;
input  [17:0] x_316_V;
input  [17:0] x_317_V;
input  [17:0] x_318_V;
input  [17:0] x_319_V;
input  [17:0] x_320_V;
input  [17:0] x_321_V;
input  [17:0] x_322_V;
input  [17:0] x_323_V;
input  [17:0] x_324_V;
input  [17:0] x_325_V;
input  [17:0] x_326_V;
input  [17:0] x_327_V;
input  [17:0] x_328_V;
input  [17:0] x_329_V;
input  [17:0] x_330_V;
input  [17:0] x_331_V;
input  [17:0] x_332_V;
input  [17:0] x_333_V;
input  [17:0] x_334_V;
input  [17:0] x_335_V;
input  [17:0] x_336_V;
input  [17:0] x_337_V;
input  [17:0] x_338_V;
input  [17:0] x_339_V;
input  [17:0] x_340_V;
input  [17:0] x_341_V;
input  [17:0] x_342_V;
input  [17:0] x_343_V;
input  [17:0] x_344_V;
input  [17:0] x_345_V;
input  [17:0] x_346_V;
input  [17:0] x_347_V;
input  [17:0] x_348_V;
input  [17:0] x_349_V;
input  [17:0] x_350_V;
input  [17:0] x_351_V;
input  [17:0] x_352_V;
input  [17:0] x_353_V;
input  [17:0] x_354_V;
input  [17:0] x_355_V;
input  [17:0] x_356_V;
input  [17:0] x_357_V;
input  [17:0] x_358_V;
input  [17:0] x_359_V;
input  [17:0] x_360_V;
input  [17:0] x_361_V;
input  [17:0] x_362_V;
input  [17:0] x_363_V;
input  [17:0] x_364_V;
input  [17:0] x_365_V;
input  [17:0] x_366_V;
input  [17:0] x_367_V;
input  [17:0] x_368_V;
input  [17:0] x_369_V;
input  [17:0] x_370_V;
input  [17:0] x_371_V;
input  [17:0] x_372_V;
input  [17:0] x_373_V;
input  [17:0] x_374_V;
input  [17:0] x_375_V;
input  [17:0] x_376_V;
input  [17:0] x_377_V;
input  [17:0] x_378_V;
input  [17:0] x_379_V;
input  [17:0] x_380_V;
input  [17:0] x_381_V;
input  [17:0] x_382_V;
input  [17:0] x_383_V;
input  [17:0] x_384_V;
input  [17:0] x_385_V;
input  [17:0] x_386_V;
input  [17:0] x_387_V;
input  [17:0] x_388_V;
input  [17:0] x_389_V;
input  [17:0] x_390_V;
input  [17:0] x_391_V;
input  [17:0] x_392_V;
input  [17:0] x_393_V;
input  [17:0] x_394_V;
input  [17:0] x_395_V;
input  [17:0] x_396_V;
input  [17:0] x_397_V;
input  [17:0] x_398_V;
input  [17:0] x_399_V;
input  [17:0] x_400_V;
input  [17:0] x_401_V;
input  [17:0] x_402_V;
input  [17:0] x_403_V;
input  [17:0] x_404_V;
input  [17:0] x_405_V;
input  [17:0] x_406_V;
input  [17:0] x_407_V;
input  [17:0] x_408_V;
input  [17:0] x_409_V;
input  [17:0] x_410_V;
input  [17:0] x_411_V;
input  [17:0] x_412_V;
input  [17:0] x_413_V;
input  [17:0] x_414_V;
input  [17:0] x_415_V;
input  [17:0] x_416_V;
input  [17:0] x_417_V;
input  [17:0] x_418_V;
input  [17:0] x_419_V;
input  [17:0] x_420_V;
input  [17:0] x_421_V;
input  [17:0] x_422_V;
input  [17:0] x_423_V;
input  [17:0] x_424_V;
input  [17:0] x_425_V;
input  [17:0] x_426_V;
input  [17:0] x_427_V;
input  [17:0] x_428_V;
input  [17:0] x_429_V;
input  [17:0] x_430_V;
input  [17:0] x_431_V;
input  [17:0] x_432_V;
input  [17:0] x_433_V;
input  [17:0] x_434_V;
input  [17:0] x_435_V;
input  [17:0] x_436_V;
input  [17:0] x_437_V;
input  [17:0] x_438_V;
input  [17:0] x_439_V;
input  [17:0] x_440_V;
input  [17:0] x_441_V;
input  [17:0] x_442_V;
input  [17:0] x_443_V;
input  [17:0] x_444_V;
input  [17:0] x_445_V;
input  [17:0] x_446_V;
input  [17:0] x_447_V;
input  [17:0] x_448_V;
input  [17:0] x_449_V;
input  [17:0] x_450_V;
input  [17:0] x_451_V;
input  [17:0] x_452_V;
input  [17:0] x_453_V;
input  [17:0] x_454_V;
input  [17:0] x_455_V;
input  [17:0] x_456_V;
input  [17:0] x_457_V;
input  [17:0] x_458_V;
input  [17:0] x_459_V;
input  [17:0] x_460_V;
input  [17:0] x_461_V;
input  [17:0] x_462_V;
input  [17:0] x_463_V;
input  [17:0] x_464_V;
input  [17:0] x_465_V;
input  [17:0] x_466_V;
input  [17:0] x_467_V;
input  [17:0] x_468_V;
input  [17:0] x_469_V;
input  [17:0] x_470_V;
input  [17:0] x_471_V;
input  [17:0] x_472_V;
input  [17:0] x_473_V;
input  [17:0] x_474_V;
input  [17:0] x_475_V;
input  [17:0] x_476_V;
input  [17:0] x_477_V;
input  [17:0] x_478_V;
input  [17:0] x_479_V;
input  [17:0] x_480_V;
input  [17:0] x_481_V;
input  [17:0] x_482_V;
input  [17:0] x_483_V;
input  [17:0] x_484_V;
input  [17:0] x_485_V;
input  [17:0] x_486_V;
input  [17:0] x_487_V;
input  [17:0] x_488_V;
input  [17:0] x_489_V;
input  [17:0] x_490_V;
input  [17:0] x_491_V;
input  [17:0] x_492_V;
input  [17:0] x_493_V;
input  [17:0] x_494_V;
input  [17:0] x_495_V;
input  [17:0] x_496_V;
input  [17:0] x_497_V;
input  [17:0] x_498_V;
input  [17:0] x_499_V;
input  [17:0] x_500_V;
input  [17:0] x_501_V;
input  [17:0] x_502_V;
input  [17:0] x_503_V;
input  [17:0] x_504_V;
input  [17:0] x_505_V;
input  [17:0] x_506_V;
input  [17:0] x_507_V;
input  [17:0] x_508_V;
input  [17:0] x_509_V;
input  [17:0] x_510_V;
input  [17:0] x_511_V;
input  [17:0] x_512_V;
input  [17:0] x_513_V;
input  [17:0] x_514_V;
input  [17:0] x_515_V;
input  [17:0] x_516_V;
input  [17:0] x_517_V;
input  [17:0] x_518_V;
input  [17:0] x_519_V;
input  [17:0] x_520_V;
input  [17:0] x_521_V;
input  [17:0] x_522_V;
input  [17:0] x_523_V;
input  [17:0] x_524_V;
input  [17:0] x_525_V;
input  [17:0] x_526_V;
input  [17:0] x_527_V;
input  [17:0] x_528_V;
input  [17:0] x_529_V;
input  [17:0] x_530_V;
input  [17:0] x_531_V;
input  [17:0] x_532_V;
input  [17:0] x_533_V;
input  [17:0] x_534_V;
input  [17:0] x_535_V;
input  [17:0] x_536_V;
input  [17:0] x_537_V;
input  [17:0] x_538_V;
input  [17:0] x_539_V;
input  [17:0] x_540_V;
input  [17:0] x_541_V;
input  [17:0] x_542_V;
input  [17:0] x_543_V;
input  [17:0] x_544_V;
input  [17:0] x_545_V;
input  [17:0] x_546_V;
input  [17:0] x_547_V;
input  [17:0] x_548_V;
input  [17:0] x_549_V;
input  [17:0] x_550_V;
input  [17:0] x_551_V;
input  [17:0] x_552_V;
input  [17:0] x_553_V;
input  [17:0] x_554_V;
input  [17:0] x_555_V;
input  [17:0] x_556_V;
input  [17:0] x_557_V;
input  [17:0] x_558_V;
input  [17:0] x_559_V;
input  [17:0] x_560_V;
input  [17:0] x_561_V;
input  [17:0] x_562_V;
input  [17:0] x_563_V;
input  [17:0] x_564_V;
input  [17:0] x_565_V;
input  [17:0] x_566_V;
input  [17:0] x_567_V;
input  [17:0] x_568_V;
input  [17:0] x_569_V;
input  [17:0] x_570_V;
input  [17:0] x_571_V;
input  [17:0] x_572_V;
input  [17:0] x_573_V;
input  [17:0] x_574_V;
input  [17:0] x_575_V;
input  [17:0] x_576_V;
input  [17:0] x_577_V;
input  [17:0] x_578_V;
input  [17:0] x_579_V;
input  [17:0] x_580_V;
input  [17:0] x_581_V;
input  [17:0] x_582_V;
input  [17:0] x_583_V;
input  [17:0] x_584_V;
input  [17:0] x_585_V;
input  [17:0] x_586_V;
input  [17:0] x_587_V;
input  [17:0] x_588_V;
input  [17:0] x_589_V;
input  [17:0] x_590_V;
input  [17:0] x_591_V;
input  [17:0] x_592_V;
input  [17:0] x_593_V;
input  [17:0] x_594_V;
input  [17:0] x_595_V;
input  [17:0] x_596_V;
input  [17:0] x_597_V;
input  [17:0] x_598_V;
input  [17:0] x_599_V;
input  [17:0] x_600_V;
input  [17:0] x_601_V;
input  [17:0] x_602_V;
input  [17:0] x_603_V;
input  [17:0] x_604_V;
input  [17:0] x_605_V;
input  [17:0] x_606_V;
input  [17:0] x_607_V;
input  [17:0] x_608_V;
input  [17:0] x_609_V;
input  [17:0] x_610_V;
input  [17:0] x_611_V;
input  [17:0] x_612_V;
input  [17:0] x_613_V;
input  [17:0] x_614_V;
input  [17:0] x_615_V;
input  [17:0] x_616_V;
input  [17:0] x_617_V;
input  [17:0] x_618_V;
input  [17:0] x_619_V;
input  [17:0] x_620_V;
input  [17:0] x_621_V;
input  [17:0] x_622_V;
input  [17:0] x_623_V;
input  [17:0] x_624_V;
input  [17:0] x_625_V;
input  [17:0] x_626_V;
input  [17:0] x_627_V;
input  [17:0] x_628_V;
input  [17:0] x_629_V;
input  [17:0] x_630_V;
input  [17:0] x_631_V;
input  [17:0] x_632_V;
input  [17:0] x_633_V;
input  [17:0] x_634_V;
input  [17:0] x_635_V;
input  [17:0] x_636_V;
input  [17:0] x_637_V;
input  [17:0] x_638_V;
input  [17:0] x_639_V;
input  [17:0] x_640_V;
input  [17:0] x_641_V;
input  [17:0] x_642_V;
input  [17:0] x_643_V;
input  [17:0] x_644_V;
input  [17:0] x_645_V;
input  [17:0] x_646_V;
input  [17:0] x_647_V;
input  [17:0] x_648_V;
input  [17:0] x_649_V;
input  [17:0] x_650_V;
input  [17:0] x_651_V;
input  [17:0] x_652_V;
input  [17:0] x_653_V;
input  [17:0] x_654_V;
input  [17:0] x_655_V;
input  [17:0] x_656_V;
input  [17:0] x_657_V;
input  [17:0] x_658_V;
input  [17:0] x_659_V;
input  [17:0] x_660_V;
input  [17:0] x_661_V;
input  [17:0] x_662_V;
input  [17:0] x_663_V;
input  [17:0] x_664_V;
input  [17:0] x_665_V;
input  [17:0] x_666_V;
input  [17:0] x_667_V;
input  [17:0] x_668_V;
input  [17:0] x_669_V;
input  [17:0] x_670_V;
input  [17:0] x_671_V;
input  [17:0] x_672_V;
input  [17:0] x_673_V;
input  [17:0] x_674_V;
input  [17:0] x_675_V;
input  [17:0] x_676_V;
input  [17:0] x_677_V;
input  [17:0] x_678_V;
input  [17:0] x_679_V;
input  [17:0] x_680_V;
input  [17:0] x_681_V;
input  [17:0] x_682_V;
input  [17:0] x_683_V;
input  [17:0] x_684_V;
input  [17:0] x_685_V;
input  [17:0] x_686_V;
input  [17:0] x_687_V;
input  [17:0] x_688_V;
input  [17:0] x_689_V;
input  [17:0] x_690_V;
input  [17:0] x_691_V;
input  [17:0] x_692_V;
input  [17:0] x_693_V;
input  [17:0] x_694_V;
input  [17:0] x_695_V;
input  [17:0] x_696_V;
input  [17:0] x_697_V;
input  [17:0] x_698_V;
input  [17:0] x_699_V;
input  [17:0] x_700_V;
input  [17:0] x_701_V;
input  [17:0] x_702_V;
input  [17:0] x_703_V;
input  [17:0] x_704_V;
input  [17:0] x_705_V;
input  [17:0] x_706_V;
input  [17:0] x_707_V;
input  [17:0] x_708_V;
input  [17:0] x_709_V;
input  [17:0] x_710_V;
input  [17:0] x_711_V;
input  [17:0] x_712_V;
input  [17:0] x_713_V;
input  [17:0] x_714_V;
input  [17:0] x_715_V;
input  [17:0] x_716_V;
input  [17:0] x_717_V;
input  [17:0] x_718_V;
input  [17:0] x_719_V;
input  [17:0] x_720_V;
input  [17:0] x_721_V;
input  [17:0] x_722_V;
input  [17:0] x_723_V;
input  [17:0] x_724_V;
input  [17:0] x_725_V;
input  [17:0] x_726_V;
input  [17:0] x_727_V;
input  [17:0] x_728_V;
input  [17:0] x_729_V;
input  [17:0] x_730_V;
input  [17:0] x_731_V;
input  [17:0] x_732_V;
input  [17:0] x_733_V;
input  [17:0] x_734_V;
input  [17:0] x_735_V;
input  [17:0] x_736_V;
input  [17:0] x_737_V;
input  [17:0] x_738_V;
input  [17:0] x_739_V;
input  [17:0] x_740_V;
input  [17:0] x_741_V;
input  [17:0] x_742_V;
input  [17:0] x_743_V;
input  [17:0] x_744_V;
input  [17:0] x_745_V;
input  [17:0] x_746_V;
input  [17:0] x_747_V;
input  [17:0] x_748_V;
input  [17:0] x_749_V;
input  [17:0] x_750_V;
input  [17:0] x_751_V;
input  [17:0] x_752_V;
input  [17:0] x_753_V;
input  [17:0] x_754_V;
input  [17:0] x_755_V;
input  [17:0] x_756_V;
input  [17:0] x_757_V;
input  [17:0] x_758_V;
input  [17:0] x_759_V;
input  [17:0] x_760_V;
input  [17:0] x_761_V;
input  [17:0] x_762_V;
input  [17:0] x_763_V;
input  [17:0] x_764_V;
input  [17:0] x_765_V;
input  [17:0] x_766_V;
input  [17:0] x_767_V;
input  [17:0] x_768_V;
input  [17:0] x_769_V;
input  [17:0] x_770_V;
input  [17:0] x_771_V;
input  [17:0] x_772_V;
input  [17:0] x_773_V;
input  [17:0] x_774_V;
input  [17:0] x_775_V;
input  [17:0] x_776_V;
input  [17:0] x_777_V;
input  [17:0] x_778_V;
input  [17:0] x_779_V;
input  [17:0] x_780_V;
input  [17:0] x_781_V;
input  [17:0] x_782_V;
input  [17:0] x_783_V;
output  [17:0] score_0_V;
output   score_0_V_ap_vld;
input  [17:0] score_1_V;
input  [17:0] score_2_V;
input  [17:0] score_3_V;
input  [17:0] score_4_V;
input  [17:0] score_5_V;
input  [17:0] score_6_V;
input  [17:0] score_7_V;
input  [17:0] score_8_V;
input  [17:0] score_9_V;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg score_0_V_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_11001;
wire   [17:0] grp_decision_function_2_fu_2083_ap_return;
reg   [17:0] scores_0_0_V_write_reg_2680;
wire   [17:0] grp_decision_function_1_fu_2149_ap_return;
reg   [17:0] scores_1_0_V_write_reg_2685;
wire   [17:0] grp_decision_function_fu_2211_ap_return;
reg   [17:0] scores_2_0_V_write_reg_2690;
reg    ap_block_pp0_stage0_subdone;
reg    grp_decision_function_2_fu_2083_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call873;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call873;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call873;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call873;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call873;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call873;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call873;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call873;
reg    ap_block_pp0_stage0_11001_ignoreCallOp86;
reg    grp_decision_function_1_fu_2149_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call874;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call874;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call874;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call874;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call874;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call874;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call874;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call874;
reg    ap_block_pp0_stage0_11001_ignoreCallOp87;
reg    grp_decision_function_fu_2211_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call875;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call875;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call875;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call875;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call875;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call875;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call875;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call875;
reg    ap_block_pp0_stage0_11001_ignoreCallOp88;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001;
wire   [17:0] tmp_fu_2273_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to6;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
end

decision_function_2 grp_decision_function_2_fu_2083(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x_99_V_read(x_99_V),
    .x_152_V_read(x_152_V),
    .x_213_V_read(x_213_V),
    .x_267_V_read(x_267_V),
    .x_290_V_read(x_290_V),
    .x_317_V_read(x_317_V),
    .x_318_V_read(x_318_V),
    .x_323_V_read(x_323_V),
    .x_350_V_read(x_350_V),
    .x_374_V_read(x_374_V),
    .x_380_V_read(x_380_V),
    .x_383_V_read(x_383_V),
    .x_400_V_read(x_400_V),
    .x_406_V_read(x_406_V),
    .x_413_V_read(x_413_V),
    .x_429_V_read(x_429_V),
    .x_435_V_read(x_435_V),
    .x_485_V_read(x_485_V),
    .x_488_V_read(x_488_V),
    .x_489_V_read(x_489_V),
    .x_490_V_read(x_490_V),
    .x_514_V_read(x_514_V),
    .x_549_V_read(x_549_V),
    .x_568_V_read(x_568_V),
    .x_570_V_read(x_570_V),
    .x_625_V_read(x_625_V),
    .x_627_V_read(x_627_V),
    .x_630_V_read(x_630_V),
    .x_657_V_read(x_657_V),
    .x_658_V_read(x_658_V),
    .x_710_V_read(x_710_V),
    .ap_return(grp_decision_function_2_fu_2083_ap_return),
    .ap_ce(grp_decision_function_2_fu_2083_ap_ce)
);

decision_function_1 grp_decision_function_1_fu_2149(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x_126_V_read(x_126_V),
    .x_155_V_read(x_155_V),
    .x_162_V_read(x_162_V),
    .x_210_V_read(x_210_V),
    .x_213_V_read(x_213_V),
    .x_235_V_read(x_235_V),
    .x_245_V_read(x_245_V),
    .x_265_V_read(x_265_V),
    .x_269_V_read(x_269_V),
    .x_316_V_read(x_316_V),
    .x_319_V_read(x_319_V),
    .x_320_V_read(x_320_V),
    .x_345_V_read(x_345_V),
    .x_348_V_read(x_348_V),
    .x_350_V_read(x_350_V),
    .x_374_V_read(x_374_V),
    .x_401_V_read(x_401_V),
    .x_405_V_read(x_405_V),
    .x_437_V_read(x_437_V),
    .x_455_V_read(x_455_V),
    .x_461_V_read(x_461_V),
    .x_463_V_read(x_463_V),
    .x_497_V_read(x_497_V),
    .x_511_V_read(x_511_V),
    .x_514_V_read(x_514_V),
    .x_569_V_read(x_569_V),
    .x_573_V_read(x_573_V),
    .x_654_V_read(x_654_V),
    .x_655_V_read(x_655_V),
    .ap_return(grp_decision_function_1_fu_2149_ap_return),
    .ap_ce(grp_decision_function_1_fu_2149_ap_ce)
);

decision_function grp_decision_function_fu_2211(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x_99_V_read(x_99_V),
    .x_154_V_read(x_154_V),
    .x_155_V_read(x_155_V),
    .x_157_V_read(x_157_V),
    .x_205_V_read(x_205_V),
    .x_210_V_read(x_210_V),
    .x_236_V_read(x_236_V),
    .x_288_V_read(x_288_V),
    .x_318_V_read(x_318_V),
    .x_327_V_read(x_327_V),
    .x_347_V_read(x_347_V),
    .x_378_V_read(x_378_V),
    .x_383_V_read(x_383_V),
    .x_398_V_read(x_398_V),
    .x_408_V_read(x_408_V),
    .x_435_V_read(x_435_V),
    .x_454_V_read(x_454_V),
    .x_461_V_read(x_461_V),
    .x_466_V_read(x_466_V),
    .x_487_V_read(x_487_V),
    .x_516_V_read(x_516_V),
    .x_524_V_read(x_524_V),
    .x_542_V_read(x_542_V),
    .x_578_V_read(x_578_V),
    .x_591_V_read(x_591_V),
    .x_598_V_read(x_598_V),
    .x_636_V_read(x_636_V),
    .x_655_V_read(x_655_V),
    .x_660_V_read(x_660_V),
    .ap_return(grp_decision_function_fu_2211_ap_return),
    .ap_ce(grp_decision_function_fu_2211_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        scores_0_0_V_write_reg_2680 <= grp_decision_function_2_fu_2083_ap_return;
        scores_1_0_V_write_reg_2685 <= grp_decision_function_1_fu_2149_ap_return;
        scores_2_0_V_write_reg_2690 <= grp_decision_function_fu_2211_ap_return;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to6 = 1'b1;
    end else begin
        ap_idle_pp0_0to6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp87))) begin
        grp_decision_function_1_fu_2149_ap_ce = 1'b1;
    end else begin
        grp_decision_function_1_fu_2149_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp86))) begin
        grp_decision_function_2_fu_2083_ap_ce = 1'b1;
    end else begin
        grp_decision_function_2_fu_2083_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp88))) begin
        grp_decision_function_fu_2211_ap_ce = 1'b1;
    end else begin
        grp_decision_function_fu_2211_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        score_0_V_ap_vld = 1'b1;
    end else begin
        score_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp86 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp87 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp88 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call873 = (ap_start == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call874 = (ap_start == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call875 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call873 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call874 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call875 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call873 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call874 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call875 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call873 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call874 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call875 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call873 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call874 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call875 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call873 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call874 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call875 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call873 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call874 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call875 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call873 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call874 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call875 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign score_0_V = (tmp_fu_2273_p2 + scores_0_0_V_write_reg_2680);

assign tmp_fu_2273_p2 = (scores_1_0_V_write_reg_2685 + scores_2_0_V_write_reg_2690);

endmodule //my_prj
